### ISSUE TITLE
Missing checkboxes on legendary skins

### ISSUE THREAD

**Issue by dyd4dsh7** [Js41637/Overwatch-Item-Tracker#101]
The checkboxes are missing on all legendary skins in all the event pages.
![capture](https://cloud.githubusercontent.com/assets/12858646/25790695/faa41e30-340e-11e7-86e2-8f6c7b401689.PNG)

**Comment by Js41637** [comment]
@DirtDiglett

**Comment by Js41637** [comment]
Fixed in commit effcc1ead86359eacebc131294f1f25991eedbaf

**Comment by Js41637** [comment]
Thanks for the heads up.

**Comment by DirtDiglett** [comment]
Yeah that was my oversight. Oops.
