### ISSUE TITLE
Item count on heroes doesn't match in-game numbers

### ISSUE THREAD

**Issue by user004** [Js41637/Overwatch-Item-Tracker#103]
**To replicate**:
1. Go into a specific hero filter (example: https://js41637.github.io/Overwatch-Item-Tracker/#/heroes/junkrat)
1. Check one of the items from the "Icons" section
1. See total count (X/Y) go up

Since player icons aren't purchase-able, and therefore aren't attached to heroes, the in-game counter does not include them.

**Comment by user004** [comment]
Also, I'm down to fork and try to fix myself, just late, and I wanted to submit the bug before I forget.

**Comment by Js41637** [comment]
This is kinda intended but I've already got a new version on the way with the option to not include Icons in the total.

**Comment by user004** [comment]
Well then, nevermind, and thanks for the effort in making this!
