### ISSUE TITLE
Anniversary Event 

### ISSUE THREAD

**Issue by cinnamennen** [Js41637/Overwatch-Item-Tracker#104]
need to add in the new items

**Comment by chickdan** [comment]
The event just started... I'm sure the owner knows they need to be added.

**Comment by SuricateCan** [comment]
BUMP! ;)

**Comment by DirtDiglett** [comment]
Yeah Jayess is Australian, and the event started at 1AM our time... He's working on the data and stuff and done most of it already, and I'll be doing some of the aesthetic stuff when I get home from work.

**Comment by Js41637** [comment]
let me sleep pls

**Comment by Argos1024** [comment]
Let me know if randos off the internet can help capture images, videos, etc and I can help if needed.

**Comment by Js41637** [comment]
It's ok, I have some strict guidelines I follow when taking images and videos now and the process is pretty quick. I have a lot of scripts that automate the process.

Thanks though.

**Comment by Argos1024** [comment]
Understood. GLHF and get some sleep.

**Comment by Xuerian** [comment]
I'm sure you've noticed, but https://playoverwatch.com/en-gb/events/anniversary/ now has rendered previews of major items. The dances, at least.

Though I assume you may just want to stick with what you're already doing.

Which, by the way, thanks for doing.

**Comment by Js41637** [comment]
Oh right this is dun
