### ISSUE TITLE
Add golden weapons

### ISSUE THREAD

**Issue by ziozxzioz** [Js41637/Overwatch-Item-Tracker#111]
This is the only thing that bugs me about the project, all of the item count for every character are the same as the in-game ones _except_ for the ones that have a golden weapon. Is there any way you can add this? Even if it doesn't have the golden weapon preview it would help a lot.
Thanks! I really love this project!

**Comment by ziozxzioz** [comment]
sorry, didn't realize it was already open

**Comment by Js41637** [comment]
I couldn't live with myself if I added them without a preview, I do have some plans on adding them however.
