### ISSUE TITLE
Missing spray for Ana

### ISSUE THREAD

**Issue by WouterVanherck** [Js41637/Overwatch-Item-Tracker#112]
This wasn't in the patch notes and I don't know when they added it, but they've added a "pillow" spray for Ana. It's not currently on the site yet, so does the data need to be updated?
Proof - [Ingame screenshot](http://imgur.com/a/d1Bhl)

**Comment by Js41637** [comment]
Yeah they added it in the PTR and I already knew about it before hand. I just have been busy the past couple days but I just added this and updated some other stuff. HotS items are no longer Blizzard Exclusive and one of the player icons got renamed.

**Comment by WouterVanherck** [comment]
Appreciate the quick action! If there's anything you can use some help with, let us know (I should graduate as an application developer this year, so code is something me and others can help on too)!

Also: this is worth a heads up -> Changing the HotS items to not-blizzard exclusive made it so that it isn't selected anymore. I would have missed this if you wouldn't have mentioned it. This brings me to the topic of a change log that could be implemented on the website. Should I make a new issue/enhancement request for that or do you think that it's not worth?

**Comment by Js41637** [comment]
It should still be selected, selected items are based off item ids which are just a slug of the name.

**Comment by WouterVanherck** [comment]
Must have accidently missed it, thanks.
Does the suggestion for a change log seem usable?

**Comment by Js41637** [comment]
Yeah sure.
