### ISSUE TITLE
Price counter text a bit confusing

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#114]
The text for the price counter on the right side is more confusing than helpful.
Currently the text is this:

> Cost to purchase remaining items
> xxx in total
> xxx to buy selected items

Since there isn't punctuation between the lines I couldn't understand why the price I'm seeing isn't the same as the total price or the selected items price. Also, as a side remark, using different words, "purchase" and "buy" for the same action is also confusing. Makes it feel like they are different actions.

I'd re-phrase the text and maybe even add the price shown on screen to the box. Something like (and maybe with this don't center the text, but align left):

> Cost to purchase remaining items: xxx.
> Cost to purchase selected items: xxx.
> Cost to purchase all items: xxx.

**Comment by Js41637** [comment]
Implemented
