### ISSUE TITLE
DirtDiglett's theme for the Summer Games shows the Price Counter and the Legendary Skin price (it shouldn't)

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#115]
In DirtDiglett's theme for the Summer Games, the Price Counter and the Legendary Skin cost are shown.

Expected: Shouldn't appear, as items couldn't have been bought.

**Comment by Js41637** [comment]
Summer games is coming back soon, might not be a problemo.

**Comment by Gonzom** [comment]
Also true

**Comment by DirtDiglett** [comment]
You watch, I'll fix it when I get home and then Summer Games will come back and you'll be able to buy stuff and I'll get grumpy and have to bring it back...

**Comment by Js41637** [comment]
This is soon going to be irrelevant as you will be able to buy them, closing.
