### ISSUE TITLE
Spray text explanation slight re-wording 

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#116]
The Winter Wonderland and Year of the Rooster events have an explanation text for the sprays. Both texts are almost similar with a few exceptions with the main difference being that The Year of the Rooster one uses the words "other spray" instead of the name of the spray itself, which is "Dragon spray". I've adjusted both texts to fix that issue and a few minor ones and made both texts the same.

Current:
Winter Wonderland :
> This event added two sprays for every character, the checkboxes are for the normal sprays and the circle boxes are for each characters 'Ornament' Spray

Year of the Rooster:
> This event added two sprays for every character, the checkboxes are for the normal sprays and the circle boxes are for the other spray

Change to:
Winter Wonderland:
> This event added two sprays for every character. The checkboxes are for the normal sprays and the circle boxes are for the 'Ornament' sprays.

Year of the Rooster:
> This event added two sprays for every character. The checkboxes are for the normal sprays and the circle boxes are for the 'Dragon Dance' sprays.

**Comment by Js41637** [comment]
Ah yeah i'll update this.
