### ISSUE TITLE
Circle spray box near title is interactive

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#117]
In the Winder Wonderland and Year of the Rooster, the circle box near the spray title (not the ones near the character spray), which is supposed to be only visual, is actually interactive.

Expected: Shouldn't be interactive.

**Comment by Js41637** [comment]
I kinda like it, it's like a demo of how to click a checkbox :)

**Comment by Gonzom** [comment]
😸
