### ISSUE TITLE
The 'Selected'/'Unselected' filter option appears in the "Currently filtering' text before the "Achievement" option

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#120]
The 'Selected'/'Unselected' filter option appears in the "Currently filtering' text before the "Achievement" option.

Since the order is always pre-defined and not based on the order selected by the user, I'd say that this option should be the last in the line and not before the "Achievement" option.

**Comment by Js41637** [comment]
So you want it at the end? I mean I can put it anywhere but yes, it is always in a fixed position. It goes events, achievement, hero, selected now.
