### ISSUE TITLE
Doomfist and D.Va out of alphabetical order

### ISSUE THREAD

**Issue by fuzzys** [Js41637/Overwatch-Item-Tracker#125]
Ingame in the hero gallery, D.Va appears before Doomfist, but on the item tracker, Doomfist appears before D.Va. Changing this to match the game would make it easier to add items while going through characters in Hero Gallery order.

**Comment by Js41637** [comment]
Fixed in 3a827d47682a601f399a0c5bfbe9cc2d835bdf92
