### ISSUE TITLE
Show total costs next to remaining costs

### ISSUE THREAD

**Issue by Selbi182** [Js41637/Overwatch-Item-Tracker#13]
Hey there, this is not an issue, just a feature request (dunno how else to reach out for this). Basically, I use the checklist as a wishlist instead for items I don't have yet but want to. It should then show the total amount of credits required for that.

To do that now I have to select everything I **don't** want. It's pretty hackish.

Can you do it so it displays the total cost of all selected items next to the one that displays the remaining cost? So that as you click more items, one counter goes up and one goes down.

Alternatively, clicking on the counter to toggle the behavior could also work.

Would be cool if you could add this. Love the work you do! 👍

**Comment by Js41637** [comment]
I'll see what I can do.

**Comment by Js41637** [comment]
dun-ish, if you hover over cost remaining it will show you the total cost and the cost to buy currently selected items, tho I do have some ideas to improve on this in the future.
