### ISSUE TITLE
Summer Games 2017 layout on mobile is messed up

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#132]
The new Summer Games layout on a mobile phone is messed up.
![summergames2](https://user-images.githubusercontent.com/16445220/29118446-ade2ccdc-7d0a-11e7-9456-5504674b5fc4.png)
![summergames1](https://user-images.githubusercontent.com/16445220/29118447-ade556b4-7d0a-11e7-84ec-330fd00accf9.png)

**Comment by Js41637** [comment]
clear your caches, recent commit should fix.

**Comment by Gonzom** [comment]
All is fixed except the overall progress bar
