### ISSUE TITLE
Summer Games icon grouping

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#133]
Could the Summer Games icons be grouped by sports/flags/other?

**Comment by Js41637** [comment]
I am not able to manually sort the items.

**Comment by Gonzom** [comment]
Nevermind, I just noticed its ordered like that, just left-to-right and not top-to-bottom, that's why I missed it.

**Comment by Js41637** [comment]
Yeah I would prefer them go top-to-bottom however i'm not sure if I can as it's not using a flexbox like the others. I might look into it.
