### ISSUE TITLE
Summer Games 2016

### ISSUE THREAD

**Issue by dyd4dsh7** [Js41637/Overwatch-Item-Tracker#134]
Should the player icon and the spray be names Summer Games 2016 not just Summer Games, cause the 2017 ones have the same name.

**Comment by Js41637** [comment]
Yeah this was a side effect of me removing dates from the names as it took up extra space. I'll add them back for Summer Games but only Summer Games 2016 spray and icon are called `Summer Games 2016` the 2017 spray is just called `Summer Games`, for now. In hindesight I should have named it Summer Games 2017 but I can't change the id anymore.
