### ISSUE TITLE
NEW Tag

### ISSUE THREAD

**Issue by dyd4dsh7** [Js41637/Overwatch-Item-Tracker#136]
Is there a way to show what's new for the new event, like what they have some for the event website https://playoverwatch.com/en-us/events/summer-games/ 

Having this would also be good for future events that are repeats.

**Comment by Js41637** [comment]
I initially had it but it adds way to much clutter. I think i might add it again but make it an option because having 25 new icons on the voicelines would look stupid.

**Comment by Gonzom** [comment]
I support this request

**Comment by dyd4dsh7** [comment]
Maybe just making it a filter

**Comment by Js41637** [comment]
this was done a while ago
