### ISSUE TITLE
Player icons are Rare(blue), but colored in the tracker as Common(white)

### ISSUE THREAD

**Issue by dargaCode** [Js41637/Overwatch-Item-Tracker#141]
http://overwatch.wikia.com/wiki/Loot_Box#Contents

I've been paying closer attention to rarities with this new loot box tuning, and never noticed that Icons weren't common until now.

**Comment by Js41637** [comment]
Yes this is intentional. I extract data from the game directly and they come back as a Rare quality. The code kind of judges the price of an item by it's quality and as such I strip qualities from icons as they are not purchasable.

**Comment by dargaCode** [comment]
Ah ok, do you think it would be too hacky to just add the blue color back via CSS?

**Comment by Js41637** [comment]
Closing this issue in favor of the newer one made #196
