### ISSUE TITLE
Total numbers are sometimes colored on the Summer Games page with the secondary theme

### ISSUE THREAD

**Issue by ThePsionic** [Js41637/Overwatch-Item-Tracker#142]
![image](https://user-images.githubusercontent.com/842080/29439867-0128db36-83c1-11e7-8c2e-9ce039341c0d.png)
Some totals are grey as normal and some are colored with the same color as the rarity of all the items contained within (or green in case of voice lines).

**Comment by Gonzom** [comment]
I think this change also caused all event items to lose their rarity color.

**Comment by Js41637** [comment]
The items aren't colored on the other theme afaik.
