### ISSUE TITLE
JSON Data Incomplete

### ISSUE THREAD

**Issue by Azrane** [Js41637/Overwatch-Item-Tracker#143]
In exporting JSON data for my own uses, I've noticed that only items that have been checked (and those that have been subsequently unchecked) will be listed in the JSON export data. Nothing that hasn't previously been checked will be listed. Could this be changed so that all items will be listed in the export data, regardless of status?

**Comment by Js41637** [comment]
I'm not sure as to why this would be useful.

**Comment by francoisgervais** [comment]
If you're looking to have a master set of items against which you want to compare your owned items, export your current set, toggle select all items, export that too, re-import the first one and do whatever you need to do with the two jsons you generated.

**Comment by Js41637** [comment]
Also if you wish to use the data that the site uses you can just use the raw data files found in the repo. https://github.com/Js41637/Overwatch-Item-Tracker/blob/master/data/items.json
