### ISSUE TITLE
Winter Wonderland 2016 - Ornament Spray Counter Broken

### ISSUE THREAD

**Issue by Borgleader** [Js41637/Overwatch-Item-Tracker#145]
Checking the square checkbox removes 75 credits from the counter, unchecking it adds 75 credits. This one works as expected. However, the behavior of the round checkbox seems to depend on the state of the square one. If the square one is unchecked it keeps adding 75 credits every time you click it, if it's checked it keeps removing 75 credits every time it's clicked.

Tried with:
Chrome Version 60.0.3112.101
Firefox 55.0.3

The only workaround I have so far is to reload the page to force a recompute of the correct amount.

**Comment by Js41637** [comment]
Thanks. I think this has been a bug for a while now I just never noticed it. According to Git i refactored the costs calculating 4 months ago so it has probably been broken for that long.
