### ISSUE TITLE
Add filter [Selected/Unselected] to each event page

### ISSUE THREAD

**Issue by anisanwesley** [Js41637/Overwatch-Item-Tracker#146]
I really liked your site and it is extremely useful for me

A cool feature could be a filter to view only selected/unselected items also on pages of event, just like heroes pages

Best Regards

**Comment by russell-matt** [comment]
Added functionality for this in pull request #160 

Functions using a button rather than the filter drop-down however. If event pages get a filter added could move the button functionality to there. 😄

**Comment by Js41637** [comment]
dun
