### ISSUE TITLE
Request - Golden guns and reduce event prices

### ISSUE THREAD

**Issue by magnusjun** [Js41637/Overwatch-Item-Tracker#147]
Include golden guns. And let event prices fall to their normal values. Blizzard is clearly intending to reduce every event item to the standard price and only keep new ones at 3x

**Comment by Js41637** [comment]
I'll update other events when they come around again. As for golden weapons... remains to be seen.

**Comment by magnusjun** [comment]
Why not reduce the prices now?

2017-09-04 11:49 GMT+02:00 Js41637 ftw <notifications@github.com>:

**Comment by vrnvorona** [comment]
Cause it is unclear if they will be lowered. Postaction is better then preaction if no certanty.

**Comment by magnusjun** [comment]
It is not unclear lol. Blizzard has made their stance very clear. Plus it's
annoying to look at a price that's tripled.

2017-09-04 18:31 GMT+02:00 vrnvorona <notifications@github.com>:

**Comment by vrnvorona** [comment]
Then it is on developers, who i respect a lot.

**Comment by magnusjun** [comment]
What do you mean? The developers has made their stance very clear and if
you respect them so much, why don't you trust their decision and lower the
displayed prices as well?

2017-09-04 18:35 GMT+02:00 vrnvorona <notifications@github.com>:

**Comment by vrnvorona** [comment]
I mean developers of tracker.

**Comment by magnusjun** [comment]
well I'm talking about Blizzard and Jeff + Team

2017-09-04 18:37 GMT+02:00 vrnvorona <notifications@github.com>:

**Comment by Js41637** [comment]
They can't be bought anyway, there is no issue.

**Comment by Js41637** [comment]
Golden weapons will be tracked in issue #65
