### ISSUE TITLE
Audio with pt-br

### ISSUE THREAD

**Issue by ViniciusAugusto** [Js41637/Overwatch-Item-Tracker#149]
How was it possible to get the audio of the heroes? I want the audio in the version with pt-br

**Comment by Js41637** [comment]
I extract the data from the game. Technically this is not possible anymore as the newer versions of the game have made it so this can no longer be done (for now) however I also cannot get other languages as you need to have the language installed. I have never done testing with other languages. Assuming the file ids are the same (I don't know) then maybe I could get other languages but if the file ids are different then there is no way as I would have no idea what voiceline is what.

Either way. I cannot get audio for other languages, sorry.

**Comment by ViniciusAugusto** [comment]
Okay @Js41637 thank you very much for the information,

if I find something out here too
