### ISSUE TITLE
Overwatch Halloween Terror 2017

### ISSUE THREAD

**Issue by dyd4dsh7** [Js41637/Overwatch-Item-Tracker#150]
You know what to do. :)

**Comment by Js41637** [comment]
wot if i forgot

**Comment by ShadiEnigmar** [comment]
Any idea how long it will take? Not trying to rush you I'm just curious.

**Comment by Js41637** [comment]
Well i'm at work at the moment. Got most of the stuff ready already it's just getting all the images and stuff that I gotta do and adjust the layout to support all the new stuff. Probably a few hours.

**Comment by Js41637** [comment]
Well it took a bit longer than expected. Sorry about that but it's finally up now!
