### ISSUE TITLE
Missing Halloween icons & 3 broken files

### ISSUE THREAD

**Issue by francoisgervais** [Js41637/Overwatch-Item-Tracker#154]
Hello,

You're missing the Halloween event logo in all hero pages. Pretty sure this affects all of them, both for 2016 & 2017 content.

The icon is still where it [should be](https://js41637.github.io/Overwatch-Item-Tracker/css/themes/dirtdiglett/resources/icons/events/HALLOWEEN_2016.svg). I think this is caused by conflicting use of "HALLOWEEN" and "HALLOWEEN_2016" in various places, for example changing any of the `event="HALLOWEEN"` to `event="HALLOWEEN_2016"` makes the icon show up correctly:

![](https://i.imgur.com/tkzaKUr.gif)

Also, the following files are 404'ing:
https://js41637.github.io/Overwatch-Item-Tracker/resources/heroes/doomfist/voicelines/doomfist-i-have-something-for-you.ogg
https://js41637.github.io/Overwatch-Item-Tracker/resources/heroes/doomfist/voicelines/doomfist-you-should-be-scared.ogg
https://js41637.github.io/Overwatch-Item-Tracker/resources/heroes/lucio/poses/lucio-pumpkin-control.jpg

I'll keep an eye out for any other issues, but so far everything else seems perfect. Thanks a bunch for the update!

**Comment by Js41637** [comment]
Yeah i know about the missing DoomFist lines. Apparently they weren't detected by my extractor...

**Comment by francoisgervais** [comment]
An additional missing file:
https://js41637.github.io/Overwatch-Item-Tracker/resources/heroes/symmetra/sprays/symmetra-victory-pose.png

The spray is just called "Victory" in game, not sure if that was changed in this update.

**Comment by Js41637** [comment]
This was fixed in #153

**Comment by Js41637** [comment]
Hmm are you saying the Pumpkin icons aren't showing up for Reaper on his hero page? They show up for me...

![image](https://user-images.githubusercontent.com/6258213/31430725-736685dc-aebd-11e7-92c8-ca23b0c78621.png)

**Comment by Js41637** [comment]
The poses issue is fixed. I dunno about those Doomfist voicelines. Can't seem to find them anywhere for some reason.

**Comment by Js41637** [comment]
found those doomfist lines
