### ISSUE TITLE
Upload to Drive feature is malfunctioning

### ISSUE THREAD

**Issue by WouterVanherck** [Js41637/Overwatch-Item-Tracker#155]
I'm happy to hear that there's been worked on a feature involving a link between the saved data and your personal Google Drive, but it seems like it's currently malfunctioning. The login works fine but it can't seem to write a file to the storage. Could this be an issue with rights? Should an empty file be present in the Drive before uploading?

**Steps to reproduce:**
1. *Authorize* and login to your Google Account
2. *Upload to Drive* and select *Yes*
3. An error will occur

**Image:**
![Error on uploading to Drive][Error]
I can't seem to insert the image, so here's the link: https://imgur.com/a/7LUrY

Besides, there's no possibility to change accounts. The only thing you're able to is logging out or in. This isn't a necessary feature but it could come in handy when people picked the wrong account

[Error]: https://imgur.com/a/7LUrY

**Comment by Js41637** [comment]
The data is stored in your Drive but it's registered as an App. Apps on Google Drive have their own storage that isn't viewable. 

Did you have anything selected when you uploaded? It works for me and the error is pretty vague. I'll do some more tests.

**Comment by WouterVanherck** [comment]
Yeah, I've got loads of things selected and the JSON validates. If there's anything I can help with, like generating a document in Drive first and sync it instead of upload or other tests, let me know.

**Comment by Js41637** [comment]
Well technically it is viewable via the api. I might add some debug code that will log a list of files apparently stored in the app storage to see if something weird has happened.

**Comment by Js41637** [comment]
Yeah I know what the issue is. Google drives api is horrible, gonna have to write a bunch of stuff probably to work around this issue.

**Comment by Js41637** [comment]
Actually wasn't as bad as I thought. Let me know if it works

**Comment by WouterVanherck** [comment]
"*Successfully uploaded to Google Drive... maybe... probably*".

I love that line! Everything seems to work, I can upload/download and even sync. Gotta say that the notice which pops up when syncing is a bit confusing and probably shouldn't popup if an upload/download has been done (if possible to check).

**Comment by Js41637** [comment]
I think it's required if you were to use the google drive on another computer. If you were to enable sync it could just overwrite the file in there with nothing as you have no items so if it needs to know if you want pull or overwrite. While the question might be obvious i'm not too sure. There's always a lot of complexities when it comes to two-way syncing.
