### ISSUE TITLE
Spray: Halloween Special has wrong description

### ISSUE THREAD

**Issue by WouterVanherck** [Js41637/Overwatch-Item-Tracker#159]
This is probably Blizzard's fault, but I wanted to point out that the spray "*Halloween Special*", acquired by completing Junkenstein's Revenge on Legendary, has the wrong description. It says "*Win Junkenstein's Revenge on Hard Difficulty*" instead.

https://imgur.com/a/5f2GO

Feel free to close this issue if this is out of your reach.

**Comment by Js41637** [comment]
This was fixed earlier, might be a caching issue? Does it still show incorrectly?

**Comment by WouterVanherck** [comment]
It seems to be shown correctly now, thanks
