### ISSUE TITLE
Halloween Event Player icons

### ISSUE THREAD

**Issue by gamerfreak820** [Js41637/Overwatch-Item-Tracker#161]
The player icons for the Halloween event aren't counting towards the total bar at the top of the screen. I get that they shouldn't count towards the currency total in the corner but the total number of items in that progress bar accounts for the number of player icons yet selecting them doesn't increase the number.

**Comment by Js41637** [comment]
Ah yeah, kind of a bug. There's a setting in Settings page to not count icons towards the total. Seems to be a bug here where it's counting them towards the overall total.

**Comment by Js41637** [comment]
Should be fixed now!
