### ISSUE TITLE
Blackwatch Icon 

### ISSUE THREAD

**Issue by VeggieGamer** [Js41637/Overwatch-Item-Tracker#162]
why is the Blackwatch icon assigned to McCree? Blackwatch belongs to reaper. As with the spray. Is spray and icon not always for the same person? As with Oni-Genji or Officer DVA?

**Comment by Js41637** [comment]
I don't make up the rules. This data comes from the game. McCree got a Blackwatch icon for Uprising with his Blackwatch skin as he use to be in Blackwatch.

Technically the icons don't belong to any hero but if you pay attention in-game if you unlock a hero themed Icon it tells you which hero it belongs to and this is where that data comes from.
