### ISSUE TITLE
Suggestion: Update bars' color with in-game colors

### ISSUE THREAD

**Issue by FrancoBits** [Js41637/Overwatch-Item-Tracker#166]
I noticed a while ago that the colors used in the hero's progression bar aren't the same as the colors used in the game. I made a list with each hero's color (they're very closely to the colors used in-game, print screen can compress and the color may vary a bit).

ANA			-	809BC4
BASTION		-	8CA08A
D.VA		-	FFA4D9
DOOMFIST	-	94645C
GENJI		-	A6FF53
HANZO		-	CAC59A
JUNKRAT		-	FBCD63
LÚCIO		-	95DA62
MCCREE		-	C16B6E
MEI			-	7DBCFB
MERCY		-	FDFACD
MOIRA		-	8C4E61
ORISA		-	569C53
PHARAH		-	4E8CD8
REAPER		-	8E5062
REINDHARDT	-	A4B0B5
ROADHOG	-	C79D63
SOLDIER: 76	-	7B88A5
SOMBRA		-	846BCA
SYMMETRA	-	9FCCDE
TORBJÖRN	-	D0857E
TRACER		-	E9A553
WIDOWMAKER-	AE7AB7
ZARYA		-	FA91C7
ZENYATTA	-	FFF793

I didn't propose a pull request because I noticed the bar has a border-top-color with a lighter color, so it's up to you to decide.

**Comment by Js41637** [comment]
I use the colors that are on the website which do indeed seem to differ from the game for some reason.

**Comment by Js41637** [comment]
![image](https://user-images.githubusercontent.com/6258213/32985735-52867658-cd15-11e7-9137-be4a22af4cb8.png)

**Comment by FrancoBits** [comment]
Whoa, I didn't know I could see my profile in the website xD
I'll keep the suggestion, I always related the in-game Hero Gallery.

**Comment by Js41637** [comment]
I gave this some thought and I looked at the games data and extracted the actual colors used however on comparison I really prefer the colors used by the website than the game. The games ones seem quite washed out whereas the websites are a lot more vibrant which I prefer.
