### ISSUE TITLE
Unable to import old data.

### ISSUE THREAD

**Issue by NoUsernameThanks** [Js41637/Overwatch-Item-Tracker#171]
Haven't had time to play in a while, came back to the site but it was black, restored my data from a .txt file. The validity checker thinks it's alright, but pressing overwrite does nothing but reloads the page.

Attached: my saved data
[OWT.txt](https://github.com/Js41637/Overwatch-Item-Tracker/files/1553201/OWT.txt)

**Comment by Js41637** [comment]
Yes the page will reload after updating, I just added it and it seemed to work? If you go to the homepage you should see each hero has a few items selected. The backup isn't very large and only a few items on each hero??

**Comment by NoUsernameThanks** [comment]
You're right, my mistake, I must've checked all the "wrong"seasonals but not the big overview.

I must've overridden my .txt file at some point, that's annoying. Hopefully the Drive integration will stop that.
