### ISSUE TITLE
Need previews of golden weapons

### ISSUE THREAD

**Issue by Js41637** [Js41637/Overwatch-Item-Tracker#175]

**Comment by djcorny** [comment]
Don't know if you've seen it, but I have all previews on [my dropbox](https://www.dropbox.com/sh/ipcu95xbg3rq6kb/AACZNEoB6hwJ3pFOPcG1Ihtta?dl=0). Or do you need images without any background?

**Comment by Js41637** [comment]
I don't think i'll be adding previews of golden weapons anytime soon.

**Comment by Js41637** [comment]
Finally here bois, high quality renders all all the golden weapons in glorious transparency.

![image](https://user-images.githubusercontent.com/6258213/50392831-da997880-07a5-11e9-8ea2-52af2f899f08.png)
