### ISSUE TITLE
Mark all commons

### ISSUE THREAD

**Issue by Watchful1** [Js41637/Overwatch-Item-Tracker#176]
With the lootbox changes earlier this year where you no longer get duplicates, I have found myself getting all the common items each event. I don't tend to bother tracking every single common item I get, even though I get them all. A simple button to mark all common items for an event as obtained would be extremely helpful.

**Comment by Js41637** [comment]
Probably won't add a button specifically for this but what I do need to do is do what the hero pages have where you can mark a whole section as owned (voicelines, sprays, etc.).

**Comment by Js41637** [comment]
Just added an options dropdown to the sections on event pages. Functions exactly the same as it does on hero page so you can mark all items selected for a specific group.
