### ISSUE TITLE
Changing between the 2 themes will cause the filter's mid section to merge with the 3rd section. Changing pages fixes it

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#178]
Changing between the 2 themes will cause the filter's mid section to merge with the 3rd section. Changing pages fixes it.

Steps to reproduce:
1. Go to "All Classes".
2. Click "Filter" - Notice 3 sections.
3. Click "Themes" and change theme.
4. Click "Filter" - Notice 2 sections.

**Comment by Js41637** [comment]
I don't think this is an issue of switching themes. I think it happens anytime you load directly onto a hero page.

**Comment by Js41637** [comment]
This issue should be fixed with recent changes made.
