### ISSUE TITLE
DirtDiglett's theme is missing item quality coloring in event pages

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#179]
DirtDiglett's theme lost along the way the item quality coloring in event pages.
Not sure if this was done deliberately or not. If it is on purpose, please reconsider adding it back.

**Comment by Js41637** [comment]
Yeah i made a bit of changes to events this update and I don't really take care of his theme so much except making sure it isn't 100% broken. A lot of the theme needs to be redone as a lot of CSS is now redundant.
