### ISSUE TITLE
Very high cpu usage when on the page

### ISSUE THREAD

**Issue by slowthgt** [Js41637/Overwatch-Item-Tracker#181]
Title says it all.

Tested on both chrome and opera.

Could be the snow effect or you added some broken script.

**Comment by Js41637** [comment]
Could be snow, page is also quite heavy normally as it uses angular and everything is generated dynamically. There is an option in the settings page to disable snow.

**Comment by slowthgt** [comment]
Yep, it was definitely the snow, really weird that it caused such a high cpu usage, but disabling it fixed it!

**Comment by Js41637** [comment]
It definitely depends on the computer because it should be using the GPU to render it but depending it could use the CPU which would cause it to go pretty high.

**Comment by slowthgt** [comment]
Yeah, it happens if you have hardware acceleration disabled, I just checked.
