### ISSUE TITLE
D.Va hero icons quantity bugged

### ISSUE THREAD

**Issue by Ravien** [Js41637/Overwatch-Item-Tracker#182]
![overwatchtrackerissue](https://user-images.githubusercontent.com/18368781/34334652-46a68eb4-e916-11e7-9a85-ba14ff2f8b79.PNG)

At least on D.Va's page, the icons is showing an inconsistent number, missing a qty of 1, and will actually drop to -1 if I uncheck them all.

**Comment by Js41637** [comment]
Did you come from the `all` page? Marking items on the `all` page does have a bug where it will affect the item count. If you refresh the page it should be fixed.

**Comment by Ravien** [comment]
Yep, that's the issue. quantities fixed now. Thanks :)
