### ISSUE TITLE
Mistake on the Halloween Terror page

### ISSUE THREAD

**Issue by Joschaliu** [Js41637/Overwatch-Item-Tracker#185]
Hi there! 
Not sure if this is the right place to report this, but I found a little mistake on the page for the Halloween Terror Event. In the box for the 2016 skins, it says Summer Games 2016 instead of Halloween Terror 2016. 

I absolutely love your tracker, keep up the great work :)

**Comment by WouterVanherck** [comment]
Seems to be fixed.
If it still says *Summer Games 2016*, I'd recommend clearing your cache (keep in mind this also clears selected items so have a backup file ready)

![Proof](https://i.imgur.com/6Xay0dL.png)

**Comment by Js41637** [comment]
Clearing you cache should not do anything, it's only if you clear Cookies / Site data. You can press CTRL F5 to request the site bypassing cache.
