### ISSUE TITLE
Lunar New Year 2018 still using the rooster icon for item things

### ISSUE THREAD

**Issue by Js41637** [Js41637/Overwatch-Item-Tracker#192]

**Comment by Gonzom** [comment]
Also the image for the event on the home page

**Comment by Js41637** [comment]
That is just your cache, press CTRL F5

**Comment by Gonzom** [comment]
You speak the truth! :)

**Comment by WouterVanherck** [comment]
I'm surprised this isn't closed yet.  
Personally, if I manage to fix an issue, I jump up to close it

**Comment by Js41637** [comment]
The issue is actually valid, the image for the event is correct however the little icons next to the items is still using the icon for Year of the Rooster, Year of the Dog got an updated icon which is more generic I think and it still needs to be added. It's a pretty minor thing.

**Comment by WouterVanherck** [comment]
My apologies, I've read it wrong. I thought it was about the banner at the top...

**Comment by Js41637** [comment]
Dun
