### ISSUE TITLE
Origins/GOTY Edition Skins and World Of Warcraft Rewards

### ISSUE THREAD

**Issue by evilgenious448** [Js41637/Overwatch-Item-Tracker#194]
Hi,

Currently the rewards for purchasing the World of Warcraft: Battle For Azeroth Collector's edition count towards the 100% character completion of characters such as Torb (2 voice lines) and Tracer (2 emotes). 
Same issue with the Overwatch Origins/GOTY Edition Skins of Pharah, Soldier, Reaper, Bastion and Tracer, these items should not count towards character completion. Also Widowmaker's pre-order Noire skin applies to this as well, along with the Blizzcon virtual ticket skins and anything else with that "B" symbol next to it.

What I mean by this is that Reaper only has 91 items you are required to collect, to get that pretty black bar filled all the way. If you own the Blackwatch Reyes skin, it will not change anything, you will still be required to get just the other 91 cosmetic items.

The way you have it currently is that it is part of the 100% completion, and your system has Reaper set as requiring 92 items, when the game only expects you to get 91.

Thank you :)

**Comment by evilgenious448** [comment]
All good man, hope it becomes a thing in the future. Love the work you put into this, a lot of people are really grateful for it!

**Comment by tjsr** [comment]
@Js41637 - I've just sent you an email on this but I believe what I was proposing I write the code for would address exactly this issue.  Let me know before I sink in any time on it.

**Comment by evilgenious448** [comment]
@tjsr May I know the proposed solution and if @Js41637 has given the go ahead for it?

**Comment by Js41637** [comment]
I just added this, special items such as Origins Edition skins, Blizzcon Skins, the Preorder Skin, and the new Mercy BCF items no longer count towards you're totals unless you have selected them.

Make sure to report any bugs if you find them.
