### ISSUE TITLE
Brigette Items

### ISSUE THREAD

**Issue by CWSensation** [Js41637/Overwatch-Item-Tracker#200]
Hi!  Just a quick heads-up that the new hero Brigette is available and live, with items to be added.

Love the tracker, and appreciate all the work that you do!

**Comment by Js41637** [comment]
Hopefully in the next few days, I've been out of town for a couple weeks so I haven't been able to update it

**Comment by WouterVanherck** [comment]
@CWSensation They're up!

**Comment by Js41637** [comment]
Yesssssssssss i'm finally home and have added the new brigitte items. Only have previews of sprays, icons and voicelines atm though. Will add Skins, Victoryposes, Emotes and intros soon.

**Comment by GlassedSilver** [comment]
Thank you so much. My 9 loot boxes that I kept closed for this moment say thank you!

**Comment by Js41637** [comment]
Sorry to keep you guys waiting!

**Comment by CWSensation** [comment]
You're the man.  :)  Thank you!

**Comment by SylvainSimon** [comment]
Thankx man ! I keep all my loot boxes at any new content :)
Your project is just usefull as fuck !

If only it was Angular 2 or higher I could have offered you a hand :)
