### ISSUE TITLE
Uprising event is now being called Overwatch Archives

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#201]
Just a heads up, the recent developer update said the name of last year's Uprising event will now be called "Overwatch Archives".

**Comment by Js41637** [comment]
Yeah i'm pretty well up to date on the on-goings of Overwatch. I browse most game files every Live/PTR patch to see what's goin on (spoiler alert, PTR is very juicy). I dunno how quick I'll be able to get the new event out as it comes out when will be out of the country, hopefully I should be able to get it up.

**Comment by Gonzom** [comment]
Can't wait to see what we're going to get then :)
