### ISSUE TITLE
Archives Event Live

### ISSUE THREAD

**Issue by essidus** [Js41637/Overwatch-Item-Tracker#202]
It's been a few hours and you don't have everything in yet!

Kidding, kidding. Figured I'd write this in now before someone else does so people aren't pounding down your door. You mentioned you'd probably be out of town so keep safe, and I'll be looking forward to opening some loot boxes once you can get everything set up!

**Comment by evilgenious448** [comment]
> The items on gallery get a "new" tag while you don't click it, so there is no problem in open a lot os boxes and check all items after update

Not if you "equip" the item you open in the lootbox, and I am sure that we are all eager to wear all of the new skins we get!

**Comment by Hsilamot** [comment]
Any comments on the admins yet? 

if you are busy what can we do to help you update the tracker?

**Comment by Js41637** [comment]
Oh sorry, forgot to comment on this. Update came a a bad time for me but hopefully I'll be able to update it tonight (7 hours) or tomorrow. Sorry for the wait, I've been travelling and on a plane for like 14 hours

**Comment by evilgenious448** [comment]
Legend, keep up the good work though. So keen to tick off that Blackwatch Moria skin <333

**Comment by Hsilamot** [comment]
As Evilgenious said, keep up the good work, and some of us do have some knowleadge about development, so, if there's anything you think we can do to help you please let us know, if not, we will wait for your return and thanks for your effort!

**Comment by Js41637** [comment]
Most of the delay is just waiting until I can extract data from the game as every patch changes how the encryption works and new content has new encryption keys which also need to be extracted from the game. Once I can get the data most of the stuff done is automated by my scripts, there usually isn't much code required.

**Comment by GoobJutsu** [comment]
Perfect timing I went to go look for it hope its up soon 
:D

**Comment by Js41637** [comment]
Ok It's live, I haven't done emote previews and I haven't really tested but everything should be there, let me know if something isn't right. I was pretty tired and had a  headache while making this lol so. Who knows what errors there are.

**Comment by Js41637** [comment]
Side note: I really need to do something about these voicelines, 3 voicelines per hero just takes up wayyy too much space. I need to condense it down somehow.

**Comment by evilgenious448** [comment]
Thanks heaps for the update. If possible could you update the icon of the event from the uprising one to the archives/retribution logo?
