### ISSUE TITLE
Missing Item From Tracker

### ISSUE THREAD

**Issue by alloradora** [Js41637/Overwatch-Item-Tracker#204]
Ana's "Merciful" skin, but maybe there's more?
I just started filling out more than events and boy is there a lot to catch up on 8T

**Comment by Js41637** [comment]
Ana's Merciful skin is there? The data on the site is pulled directly from the game so it's highly unlikely anything is missing,

**Comment by evilgenious448** [comment]
Can confirm that the merciful skin is there

**Comment by alloradora** [comment]
Oh dear, I thought it was legendary for some reason. I checked the oranges like 3 times, though!
