### ISSUE TITLE
missing bastion poses

### ISSUE THREAD

**Issue by shootistar666** [Js41637/Overwatch-Item-Tracker#211]
![image](https://user-images.githubusercontent.com/38340987/38716993-668d59f0-3efd-11e8-95d8-059c30fb4322.png)
help ;_ ;

**Comment by Js41637** [comment]
Oh poop, will fix if I manage to get out of bed as I feel like death atm

**Comment by Js41637** [comment]
Fixed in bd763f7da1ad412e7a6aae0141aa803200bccea2
