### ISSUE TITLE
OWL Skins [Twitch Rewards]

### ISSUE THREAD

**Issue by Lucetia** [Js41637/Overwatch-Item-Tracker#213]
Not sure if you are adding them or not, but the grey OWL skins that you get from Twitch cheering / annual pass aren't available.

I'm not expecting all the team ones, that's way too much lol

**Comment by Js41637** [comment]
I will have to add them all eventually. There is also the team away skins which are coming soon so, there's a Fuck load to add

**Comment by Js41637** [comment]
Closing as it is relatedto  #188
