### ISSUE TITLE
Why CSS and not SASS or Stylus?

### ISSUE THREAD

**Issue by ralts00** [Js41637/Overwatch-Item-Tracker#215]
s a question I have, why not use a CSS precompiler?

**Comment by Js41637** [comment]
Because the site is directly hosted from the repo. How do you propose I use a precompiler without any build tooling required? I'd have to compile it locally before a push every time I edited any css? It's not impossible but just a bit of a pain

**Comment by ralts00** [comment]
i propose use LESS, because compiles directly on the browser

**Comment by Js41637** [comment]
Nah I would prefer not to add extra stuff like this. The site already suffers from degraded performance, I don't want to import more libraries.

I have started work on adding some build tooling to support using SCSS.

**Comment by Js41637** [comment]
Support for SCSS has been added.
