### ISSUE TITLE
Anniversary

### ISSUE THREAD

**Issue by evilgenious448** [Js41637/Overwatch-Item-Tracker#222]
Can we get an ETA on the anniversary content update?
Very eager to open my loot boxes!

**Comment by TheTural** [comment]
When a new event comes out, the data has to be extracted, images made, etc. It takes a few hours, at least. On top of that, the developer probably has a job and can't do all that work in the middle of the day when an event releases; it usually gets set up in the evening.

**Comment by Js41637** [comment]
I would have liked to gotten it out earlier but having some trouble "cracking" the games encryption to auto extract all the data. If i'm not able to get it soon i'll have to do it all manually 😢

**Comment by evilgenious448** [comment]
Fair enough mate, sorry if it seemed like I was rushing you, was just curious of the ETA!
Hope the auto extraction works out fine and that you don't have to do it all manually. Good luck!

**Comment by Js41637** [comment]
This is now live.
