### ISSUE TITLE
Anniversary Victory Poses

### ISSUE THREAD

**Issue by evilgenious448** [Js41637/Overwatch-Item-Tracker#223]
Hey! Noticed that you didn't include some of the new anniversary victory poses added such as Mercy's and Doom's

**Comment by Js41637** [comment]
Yeah I forgot to add them to the template in the initial push as the original event didn't have any except they have since been added. You're browser has probably just cached it. CTRL-F5 should fix the issue if you use Chrome. I don't know if it works in other browsers as well.

**Comment by evilgenious448** [comment]
Thanks mate!
