### ISSUE TITLE
Incorrect total numbers 

### ISSUE THREAD

**Issue by randomjuice** [Js41637/Overwatch-Item-Tracker#225]
In anniversary event page and possibly hero pages too.

**Comment by Js41637** [comment]
You mean the amount of items it says there are? The numbers on the anniversary page line up for me.

Also hero pages are a bit different as the totals don't include special items that are exclusive such as Blizzcon Skins or the Pink Mercy stuff. When you select them the total will increase. It does it this way because this is how it works ingame.

**Comment by Gonzom** [comment]
He's right but I couldn't pin-point the problem yet. 
I have 18 anniversary icons yet the total is listed as 16.

**Comment by Js41637** [comment]
Indeed it seems the all icons aren't getting counted

**Comment by randomjuice** [comment]
Sorry, i should have been more specific. The sprays section says i have 18/27 yet i am missing 10. The player icons section says i have 36/35 yet i am still missing 1. Because of this i am unsure if the incorrect totals also carried over to sprays/player icons/possibly more sections for one or more heroes.

**Comment by Js41637** [comment]
Yeah the sprays and icons sections aren't counting the allclass versions. There are 3 "all" icons and 1 "all" spray. This is recent issue as I changed how the item calculation logic works so it's a bug. Heroes shouldn't have an issue though. The numbers are visual only, they are calculated on page load so it'll be fixed when I find the bug.

**Comment by randomjuice** [comment]
Okay, i'm just happy to help. Thanks for all of your work.

**Comment by Js41637** [comment]
Ok I think I fixed the counts on events. The "ALL" hero page has some issues with counts though.

**Comment by Js41637** [comment]
I *think* i fixed this.
