### ISSUE TITLE
"No Event" filter issues

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#226]
1. The current "No Event" filter shows "regular" items and in-addition "Blizzard" and competitive items.
Could the filter change to be just the regular items?

2. Could the name be changed to something more reflective of that. "Regular items"/"General items"/"Base items" - something along those lines.

3. The filter does not show up in the "Currently filtering:" line.

**Comment by Js41637** [comment]
I'll change it to only show "Regular Items"
