### ISSUE TITLE
Event pages' layout are slightly broken on Edge

### ISSUE THREAD

**Issue by KaeLL** [Js41637/Overwatch-Item-Tracker#227]
Just wanted to let you know. I don't think anyone cares anyway.

**Comment by Js41637** [comment]
Yeah I am aware, something weird with how Edge calculates the width.  Like a 2 column section is `width: calc(50% - 1px);` which works in every other browser but not edge. If I set it to 2px it works tho. I might fix if I have time and can be bothered using their terrible Dev Tools.

**Comment by KaeLL** [comment]
Don't rush it.
