### ISSUE TITLE
The 3 new dance animations' previews don't load

### ISSUE THREAD

**Issue by KaeLL** [Js41637/Overwatch-Item-Tracker#228]
They don't load, so it stays on the white balloon 4ever. Not sure if it's just here, but all other emotes loaded just fine, so yeah.

**Comment by Js41637** [comment]
I haven't added them yet. The dance emotes are super painful to record as I like to have them loop. You have no idea how long it took me to get the others, most of them all loop pretty seamlessly. As well as I could get them anyway.

**Comment by KaeLL** [comment]
To be honest I hadn't thought about it until now that I read your comment. I do know how painful it is. Just thought you had missed it. Take your time.

**Comment by Js41637** [comment]
This has been rectified.
