### ISSUE TITLE
Player Icons

### ISSUE THREAD

**Issue by Lucetia** [Js41637/Overwatch-Item-Tracker#230]
Originally before the update 2 hours ago I had it set to not count icons which worked.  After the update it seems no matter what the setting is, it counts the icons.  Tried toggling it on and off and nothing.  Not sure if I missed something somewhere.

**Comment by Js41637** [comment]
Not sure what you mean? I just tested on hero pages and event pages and icons are only being counted when the option is enabled. The option does not apply to the All Hero page though.

**Comment by Lucetia** [comment]
Hm...weird seems to be working now.  Not sure what was causing it to bug earlier.  For example on Ana it was showing 101 with the option on or off.  Now it shows 93 with it off.

Also, I noticed that after the icon update my numbers shifted around a lot and a lot of white items got added to the count.  I was at 89% earlier and dropped to 86% (both numbers were after the anniversary update).

**Comment by Js41637** [comment]
Yeah i was in a world of pain earlier as the code that calculated totals was completely fucked and trying to fix a long outstanding bug made it even worse. I'm 70% sure i managed to fix all the issues last night though.

**Comment by Lucetia** [comment]
Ah no worries!  Was just weird and confusing when I saw it since I had no idea what it could be.

Thanks for all the work!
