### ISSUE TITLE
Anniversary Sprays and Player Icons

### ISSUE THREAD

**Issue by evilgenious448** [Js41637/Overwatch-Item-Tracker#231]
The counter showing your progress lists the sprays as being out of /27 when there are 28 of them
And the player icons being out of /35 when there are 38 of them

**Comment by evilgenious448** [comment]
Never mind, did another cache clear and it fixed

**Comment by Js41637** [comment]
That's weird. I have been editing the logic that calculates everything, I might have broke it again at one point. I just pushed what is hopefully the last time.
