### ISSUE TITLE
Player icons are counted as "Common" items in the "Detailed Breakdown"

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#232]
The "Detailed Breakdown" counts the Player Icons as "Common" items.
**Expected:** They should be counted as "Rare" items.

**Steps to reproduce:**
1. Check stats in  "Detailed Breakdown" - "Common" total 2129; "Rare" total 275.
2. Click "Settings".
3. Click "Don't count icons".
4. Check stats in  "Detailed Breakdown" - "Common" total 1720; "Rare" total 275.

**Comment by Js41637** [comment]
Fixed.
