### ISSUE TITLE
"Inaugural Season" icon and spray have wrong icon

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#233]
The "Inaugural Season" icon and spray currently have the achievement icon but they aren't an achievement reward. They should get either the "Blizzard" one or the "OWL" one.

**Comment by Js41637** [comment]
![image](https://user-images.githubusercontent.com/6258213/40511425-f6ffda8e-5fe2-11e8-94e5-013f450be149.png)
