### ISSUE TITLE
 Making the golden guns count optional

### ISSUE THREAD

**Issue by justauser5** [Js41637/Overwatch-Item-Tracker#236]
It would be cool, just like the icons. I know that they count ingame but if we could have that as an optional on the Item Tracker it would be cool.

**Comment by KaeLL** [comment]
I really don't see any point in this.

**Comment by Js41637** [comment]
Yeah I don't really see a point to this, also i really hate editing the logic that calculates counts as it's super tricky, making icons optional was nearly the most painful moment of my life. Also the aim is to make it line up with the counts in game (even though OWL skins currently ruin this if you own any).
