### ISSUE TITLE
All Class grid view - add source icons

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#237]
When viewing the "All Class" items in the Grid View (with the icons), the item source's icon is not shown.

You are currently showing a "lock" icon for item's not yet collected, so there is a room for the icon. 
I'd place the "source" icon at the bottom right corner (where the lock currently is) and place the lock at the bottom left corner.

Also, the icons should have a transparent gradient background similar to what you have with text, as some icons are hard to see on the image (opening a separate issue for this).

**Comment by Js41637** [comment]
This is dun
