### ISSUE TITLE
All Class grid view - add a transparent gradient background to icons

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#238]
When viewing the "All Class" items in the Grid View (with the icons), the the "lock" icon is hard to see on some icons (see USA flag, Japan flag, Crusader as examples).

The icons should have a transparent gradient background similar to what you have with text, as some icons are hard to see on the image. This should make them easier to see.

**Comment by Js41637** [comment]
This is dun
