### ISSUE TITLE
All Class grid view - missing descriptions

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#239]
When viewing the "All Class" items in the Grid View (with the icons), the item descriptions are missing.

You currently are showing the name of the item, so the best scenario would be just to add another part under with the description.

**Comment by Js41637** [comment]
I don't think this is required. It's not meant to be the same as the normal page. I don't think you can even add two tooltips to an item.

**Comment by Gonzom** [comment]
That's a shame, I only use the grid view as the list one is too wall-of-text for me. Only reason I switch back is to get this information

**Comment by Js41637** [comment]
This is dun
