### ISSUE TITLE
Missing tracer spray

### ISSUE THREAD

**Issue by Queenxx97** [Js41637/Overwatch-Item-Tracker#244]
Tracer has a spray called 'Emily' which is not showing up on the list of sprays for me. Attached picture of the spray.
![image](https://user-images.githubusercontent.com/40615521/41945279-262f8c20-79a4-11e8-90b2-7c97c3ec1623.png)

**Comment by Js41637** [comment]
Yes it's a new spray, the game updated today.

**Comment by Queenxx97** [comment]
Ah right, I didn't know it was new, sweet

**Comment by randomjuice** [comment]
As well as 4 new All-class sprays and 4 new icons for the new competitive seasons.

**Comment by Js41637** [comment]
These have been added.
