### ISSUE TITLE
Scrolling is weird and overshoots

### ISSUE THREAD

**Issue by xathon** [Js41637/Overwatch-Item-Tracker#248]
When scrolling through a hero page the view sometimes "jumps" a little further when you stop scrolling.

**Comment by Js41637** [comment]
I have never encountered this nor know what you mean. What browser/OS are you using?

**Comment by xathon** [comment]
I use Vivaldi (=Chrome), but it also happened on Edge. I'll record it once I have the opportunity.

**Comment by xathon** [comment]
It was my mouse that spazzed out, sorry. It was just the first time I'd ever seen it and it wouldn't happen in other programs until today.
