### ISSUE TITLE
Add Hanzo Simple Geometry voice line

### ISSUE THREAD

**Issue by Harmon758** [Js41637/Overwatch-Item-Tracker#250]
https://us.forums.blizzard.com/en/overwatch/t/hanzo-has-simple-geometry-as-a-voiceline-on-the-ptr/145966/8

**Comment by Js41637** [comment]
I extract all my data directly from the game so it will automatically detect any new items.

**Comment by Js41637** [comment]
Closing this in favor of a generally 1.26 items issue. #249
