### ISSUE TITLE
Player icons count as 2 items

### ISSUE THREAD

**Issue by andrerfcsantos** [Js41637/Overwatch-Item-Tracker#253]
I noticed this with when trying to register my player icons for hammond, i selected all player icons in the hero view and it shows me i have 6/3 icons:

https://prntscr.com/kbk6i4

But it seems to affect all heroes. I had all player icons for reaper, when deselecting all i got -4/9:

https://prnt.sc/kbk6i5

This last result is even weirder because it indicates some icons count as 1 while other count as 2. This is evidenced by the fact that when deselecting all i got -4/9. If all icons counted as 2, a -9/9 result was expected.

**Comment by TheTural** [comment]
Non-event icons count as 2, event icons count as 1 (that's where you're seeing the discrepancy for those). I think it's just a matter of the logic that increments the total running twice on the non-event icons, whereas the event icons are properly being excluded with one of the checks.
