### ISSUE TITLE
Overwatch League skins etc?

### ISSUE THREAD

**Issue by Flenix** [Js41637/Overwatch-Item-Tracker#263]
Would it be possible to add the Overwatch league skins as something we can manually specify we have? Maybe each hero could have an "add league skin" button - mainly just so the total and skin numbers match between in-game and the tracker.

Also, the All Access Pass stuff. That would be simpler, just a checkbox for that somewhere and if we tick that, all numbers update to reflect. Lucio's emote is already available, but the League away skins you get aren't (as an example).

Thanks :D

**Comment by dargaCode** [comment]
@Js41637 I notice you get requests like this for league skins a lot, and you don't want to clog up the "real" content with tons extra. have you thought about letting people just arbitrarily increase their skin counts instead?

eg:
Sombra Skins: 18/20 [-][+]

player hits the plus button 5 times, now it shows they have 23/25 sombra skins. 

Kinda hacky but maybe you could hide it behind an option, so all the people who are worried about this can just maintain it on their own.

**Comment by Js41637** [comment]
Not a terrible idea but this seems like something that can just end up causing problems in the long run.

Either way all OWL related stuff can be discussed under the main issue. #188
