### ISSUE TITLE
lucio "dance party" emote

### ISSUE THREAD

**Issue by korgen63** [Js41637/Overwatch-Item-Tracker#265]
Hey

I contacted the support about this emote. They confirmed they made a misstake: it’s not supposed to be bought with tokens, so you can't unlock it. If you bought tokens in order to get this emote and didn’t spend them, you can ask for a refund.
I think this emote isn't supposed to be listed ingame unless you get Twitch all-access pass. To be confirmed, but in this case it should be deleted from the database (like OWL skins) ^^

**Comment by Js41637** [comment]
I will leave the icon but I will make it not count towards the totals unless it is unlocked like the Pink Mercy skins.

**Comment by Js41637** [comment]
Oh it already does this. The item will remain though. OWL skins is kinda a separate issue to this.
