### ISSUE TITLE
Sombra shows no victory poses

### ISSUE THREAD

**Issue by mikecraft900** [Js41637/Overwatch-Item-Tracker#266]
The Sombra page shows no preview or names for her victory poses, although it says VICTORY POSES 5/6.
![image](https://user-images.githubusercontent.com/9832974/43989063-e55d12f4-9d10-11e8-82e3-2b684bb6eb1f.png)

**Comment by Js41637** [comment]
Awwh shit

**Comment by Js41637** [comment]
Also wow thats a big monitor

**Comment by Js41637** [comment]
Fixed, might take a few minutes before it's visible on the site.

Thanks!
