### ISSUE TITLE
OWL Category?

### ISSUE THREAD

**Issue by DracoClaw** [Js41637/Overwatch-Item-Tracker#273]
I know one of the issues with adding the OWL Content is that it would take up space. So maybe have like an extra category, either at the end of the hero roster or with events. And then for example it could be separated by team and you have to click the icon to open that teams list. Not sure how the counter would work, because one thing a lot of people are looking for is that it shows on the hero that you have the skin. Stuff like the grey skins and the Lucio emote as well as the all star skins and even the world cup skins if they become available could all go into this category.

**Comment by Js41637** [comment]
OWL stuff is a touchy subject, i'm considering options. OWL discussion should go under the main issue #188
