### ISSUE TITLE
10 new D.Va sprays, 1 icon and 1 skin

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#274]
Incoming 11 new D.Va sprays and 1 skin - [link](https://playoverwatch.com/en-us/news/22380666?blzcmp=app)

**Comment by DracoClaw** [comment]
I'm pretty sure it's only two sprays, one icon and one skin.

**Comment by DracoClaw** [comment]
Also they were literally just announced I'm sure that he knows about them, just give him time.

**Comment by Gonzom** [comment]
Opening an issue report is not the same thing as demanding it be added right away. Also, I'm not sure these were up on the PTR as I've not seen any Overwatch YouTube video showcasing these, and it's 10 sprays (corrected my 11), you didn't count the ones earned from Twitch.

**Comment by DracoClaw** [comment]
It sounds like we are maybe talking about two different things? D.Va just got two new Nano Cola sprays along with an icon. I'm sorry if I sounded aggressive or anything, just recently I've been going through a bunch of the reports and seeing the frustration he is having with everything and even though those comments he's made are spread out I think for me it kinda just all fell together to a more recent thing.

**Comment by DracoClaw** [comment]
I apologize. I just looked into this and there are twitch drops that I didn't know about. You are correct. Sorry about the confusion.

**Comment by Gonzom** [comment]
No worries

**Comment by Js41637** [comment]
Added in d32b502769bf42d3baa336e533477cf08166d624
