### ISSUE TITLE
Pssst, Halloween sp00ky skins and items are out.

### ISSUE THREAD

**Issue by slowthgt** [Js41637/Overwatch-Item-Tracker#278]
Hope you don't have too much difficulty fetching the encryption keys.

**Comment by Js41637** [comment]
Sorry this has taken so long again, these constant changes in the game and the tooling I use made this process more tedious than I would like. Everything should be added.

Only issue I know of at the moment is some voicelines are missing previews, for some reason they refuse to be extracted from the game, thanks blizz.

**Comment by slowthgt** [comment]
No worries, just opened the issue so there would be no spam. Take care!
