### ISSUE TITLE
Previews not appearing at mouse position

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#279]
Viewing victory poses or Highlight intro (this effects other also, but these the most as they are at the bottom of the screen) causes the preview image/video to appear below the current scroll position instead at the mouse position. As an additional annoyance, when trying to scroll down and view the preview, the image disappears causing the scroll position to jump back up.

**Comment by Js41637** [comment]
I have never seen this behavior? What browser is this?

**Comment by Js41637** [comment]
nvm, i know the issue, stupid CSS
