### ISSUE TITLE
Ashe released

### ISSUE THREAD

**Issue by slowthgt** [Js41637/Overwatch-Item-Tracker#284]
But judging by the OWLib commits, I'm guessing you haven't found a way to decrypt the files?

Anyways, just putting it here as a placeholder.

**Comment by Intervencion** [comment]
Could it be possible to add Ashe w/o the files? Just with the name of the things. Cheers

**Comment by TheTural** [comment]
> Could it be possible to add Ashe w/o the files? Just with the name of the things. Cheers

It is possible, I did it for my fork. I added the data by hand-typing the json since the extractor tools weren't updated. Probably worth double checking for accuracy, but here's the heavy lifting done if js41637 wants to manually force it into master.json as a short-term solution.

[ashe.json.txt](https://github.com/Js41637/Overwatch-Item-Tracker/files/2586655/ashe.json.txt)

**Comment by Js41637** [comment]
Ashe data has been added.

**Comment by Gonzom** [comment]
Is there an update for Ashe emotes and Highlight intros?

**Comment by slowthgt** [comment]
Pretty sure they need to be recorded manually.

**Comment by Js41637** [comment]
I just added Ashe's emotes. I still need to record to highlight intros.

**Comment by slowthgt** [comment]
If you point out what you are looking for in terms of quality of in-game recording, bitrate, res and size, I (or anyone else familiar with) could help you out with those manual assets.

**Comment by Js41637** [comment]
It is actually already documented here https://github.com/Js41637/Overwatch-Item-Tracker/blob/development/helpers/ffmpeg-settings.md

**Comment by slowthgt** [comment]
hold my beer, I'll be back in a minute

**Comment by Js41637** [comment]
Highlight intros are very hard cause you gotta time it perfectly to when it starts and ends. Of course if you had a video editor this probably wouldn't be an issue but my preference was to just get it right so I wouldn't have to manually edit potentially hundreds of files to manually tune their start and end. Also this lets me just bulk reconvert them all if I want to change the settings as I keep all the raw recordings.

Also I updated the doc a bit.

**Comment by slowthgt** [comment]
https://github.com/Js41637/Overwatch-Item-Tracker/pull/301

**Comment by slowthgt** [comment]
While you might go back and re-record it, I'm closing this out
