### ISSUE TITLE
Year of the Pig

### ISSUE THREAD

**Issue by slowthgt** [Js41637/Overwatch-Item-Tracker#293]
Placeholder for the usual stuffs

**Comment by Js41637** [comment]
Update is out.

**Comment by Harmon758** [comment]
The images for Orisa's Sanye skin and Brigitte's General skin are still missing, right?

**Comment by Js41637** [comment]
Oh ye i forgot those, then I forgot that I forgot them.

**Comment by Js41637** [comment]
Fix'd
