### ISSUE TITLE
Add method for a user to import all their unlocks

### ISSUE THREAD

**Issue by Js41637** [Js41637/Overwatch-Item-Tracker#297]
A user can get an array of every item they have using an official "API" that returns the GUID of the unlock. You must be logged into playoverwatch.com for this API to work.
https://playoverwatch.com/en-us/user/unlocks/

I can get the item ids pretty easily so it shouldn't be too hard.

Because I can't load the URL from my site due to CORS a user will need to go this API and copy all the data and I'll likely need some sort of API that will return my item ids from Overwatch's GUIDs.

**Comment by slowthgt** [comment]
Seems to not be functioning as of now.

**Comment by Js41637** [comment]
They added 'security' to the endpoint, now required an extra header to be sent `x-requested-with: XMLHttpRequest` which definitely complicates things.

Thanks Blizzard.

**Comment by svanheulen** [comment]
I made a little script for downloading the unlocks. Hope it helps!

Just log into playoverwatch.com and then paste this into the javascript console and hit enter. You can access the console with ctrl+shift+k in Firefox. I don't use Chrome but I'm pretty sure it will work there too.

```javascript
var request = new XMLHttpRequest();
request.addEventListener("load", function (event) {
    var object_url = URL.createObjectURL(this.response);
    var anchor = document.createElement("a");
    anchor.setAttribute("rel", "noopener");
    anchor.setAttribute("download", "unlocks.json");
    anchor.setAttribute("href", object_url);
    anchor.dispatchEvent(new MouseEvent("click"));
    URL.revokeObjectURL(object_url);
});
request.open("GET", "/en-us/user/unlocks");
request.responseType = "blob";
request.setRequestHeader("X-Requested-With", "XMLHttpRequest");
request.send();
```

**Comment by slowthgt** [comment]
> I made a little script for downloading the unlocks. Hope it helps!
> 
> Just log into playoverwatch.com and then paste this into the javascript console and hit enter. You can access the console with ctrl+shift+k in Firefox. I don't use Chrome but I'm pretty sure it will work there too.
> 
> ```js
> var request = new XMLHttpRequest();
> request.addEventListener("load", function (event) {
>     var object_url = URL.createObjectURL(this.response);
>     var anchor = document.createElement("a");
>     anchor.setAttribute("rel", "noopener");
>     anchor.setAttribute("download", "unlocks.json");
>     anchor.setAttribute("href", object_url);
>     anchor.dispatchEvent(new MouseEvent("click"));
>     URL.revokeObjectURL(object_url);
> });
> request.open("GET", "/en-us/user/unlocks");
> request.responseType = "blob";
> request.setRequestHeader("X-Requested-With", "XMLHttpRequest");
> request.send();
> ```

Thanks, it does work on chromium based browsers too! The only thing we might need to figure out is how to connect the addresses to the items, unless we can already get that from OWLib.

**Comment by svanheulen** [comment]
@slowthgt Glad it worked! As for the item IDs, looking through the code a little, it seems like OWLib does have that information internally but I don't see any way of displaying it with DataTool... but then again there's a million options so maybe I'm just missing it (also it's pretty buggy in Linux/Wine).

**Comment by ExQDev** [comment]
What I should do with these unlocks to get it work?

**Comment by Js41637** [comment]
I haven't built anything that can do this yet but it wouldn't be hard, i could make a script or even a website where you enter the unlocks and it'll return some JSON that can be imported into the item tracker. I'll look into it soonish

**Comment by ExQDev** [comment]
Wow, nice idea,  that'll be good!
I'll better wait for it, 'cause this topic is new to me, and it'll take a lot of time to get started:)
I'd like this, 'cause now I can't see my unlocks, and I remember that I've bought the Legendary edition, but I don't remember my promised 15 skins)

**Comment by DracoClaw** [comment]
Any updates on this?

**Comment by svanheulen** [comment]
There's a couple weird things with the unlocks returned by the API.

First is that I have the game on PC and on Xbox but it only returns the unlocks for one or the other... I think it's whichever system I got a new item on last, but I haven't really tested it.

Second is that it doesn't include certain items. For instance it doesn't include any of the sprays unlocked by watching Twitch for events like Ana's Bastet challenge. It also doesn't include the skins unlocked for buying the Origins Edition version of the game. And probably other stuff that I don't have.

**Comment by Js41637** [comment]
I whipped up a site where you can now do this.

https://overwatchitemtracker.com/unlocks-parser/

**Comment by DracoClaw** [comment]
Awesome! It works pretty well! Like svanheulen said it misses any twitch drops as well as the Origins Edition skins. But I also noticed that while the JSON that is outputted included for example Reinhardt's Crusader spray, when I imported it the spray was not checked off. There are a few times something like this is happening.

**Comment by DracoClaw** [comment]
I think if you can have an option you select that is "Mark New Items" so that it goes through and adds anything not yet added, instead of overwriting everything, that'd be great. Or have the Blizzard and twitch items be persistent.

**Comment by Js41637** [comment]
Those items are not returned by the unlocks api so there is nothing i can do regarding those.

**Comment by DracoClaw** [comment]
I understand that they are not supplied. But when I import the JSON they get removed from my list, which makes sense because the json overwrites. But I'm saying since they aren't in the json is it possible that if these items are already checked you make it so they don't get unchecked?

**Comment by Js41637** [comment]
This is done, there is now a button to merge the data instead of overwriting.
