### ISSUE TITLE
Archive Text Issues

### ISSUE THREAD

**Issue by DracoClaw** [Js41637/Overwatch-Item-Tracker#302]
The text "Event should end on May 7 local time BE SURE TO GET EVERYTHING YOU WANT BY MAY 6 TO BE SAFE!" and the logo for the event are on top of each other.

Its says "OTHER UPRISING SKINS" Where it should say "OTHER ARCHIVES SKINS"

**Comment by Js41637** [comment]
I don't know what you mean by the first issue. This does not happen for me.

**Comment by TheTural** [comment]
Looks like he/she means on the alternate theme.

![JHXCzQF](https://user-images.githubusercontent.com/18756243/56365168-d01c4800-61b5-11e9-9ceb-8ae2aa824f89.png)

**Comment by slowthgt** [comment]
seems like the header is not clipping to the logo as it should, was trying to find the style sheet responsible for it, but I hate css.

**Comment by Js41637** [comment]
Fixed.
