### ISSUE TITLE
All stars stuff...?

### ISSUE THREAD

**Issue by slowthgt** [Js41637/Overwatch-Item-Tracker#303]
Two Icons and two skins, *yawn*.

Also, the background is actually freaking amazing, was gonna suggest to rerecord all Highlights and Emotes with it, but we might never get it again to keep it constant in the future.

**Comment by jarrodls** [comment]
>re-record all highlights and emotes

![image](https://user-images.githubusercontent.com/22313733/57412792-5c5de000-7235-11e9-83a8-4352fa9b8f4d.png)

**Comment by Js41637** [comment]
>re-record all highlights and emotes

![image](https://user-images.githubusercontent.com/6258213/57412819-7697be00-7235-11e9-98b2-fdfe5cf94b38.png)

**Comment by slowthgt** [comment]
I was offering to do it myself tbh

**Comment by slowthgt** [comment]
So yay or nay? The offer is still on the table.

**Comment by Js41637** [comment]
It's ok, I don't think it's worth it. Especially since it's unlikely to ever come back.

**Comment by slowthgt** [comment]
Alright, you never mentioned what is that you consider the default background btw.

**Comment by echang754** [comment]
Any plans to add the two new icons and the all stars skins from this year and last year?

**Comment by Js41637** [comment]
the 4 all star skins have been added as well as the 2 new icons
