### ISSUE TITLE
Text formatting 

### ISSUE THREAD

**Issue by DracoClaw** [Js41637/Overwatch-Item-Tracker#304]
With the Styled theme the title in the top left "Overwatch Item Tracker" is being stacked down instead of going across. Also the hero icons are not showing when you are on their page.
![2019-05-12 (2)](https://user-images.githubusercontent.com/34274162/57581578-1f5a4d80-74c2-11e9-8ad6-8492e13b10d2.png)

**Comment by Js41637** [comment]
Fixed. Don't know how it broke as I haven't made any changes and it wasn't broken before. A browser update must have broke some CSS...
