### ISSUE TITLE
Unknown voice line in roadhog page

### ISSUE THREAD

**Issue by Ldoppea** [Js41637/Overwatch-Item-Tracker#308]
Hi,

I've noticed that a the "i'm beached as, bro" voice line is missing on the item tracker's roadhog section.

But while investigating, I also noticed that the "you're a talker" voice line from the item tracker does not exist in game.

Did Blizzard removed/added those voice lines?

Here is the ingame list
![image](https://user-images.githubusercontent.com/1884255/59058041-0c0d8880-889c-11e9-848a-d7a916f0aae8.png)

And the item tracker list
![image](https://user-images.githubusercontent.com/1884255/59058060-162f8700-889c-11e9-97be-c25d735d3620.png)

Hope that helps

**Comment by Js41637** [comment]
Blizzard removed 2 of the original voicelines and replaced them. I haven't gotten around to updating them yet.

**Comment by Harmon758** [comment]
For reference: https://playoverwatch.com/en-us/news/patch-notes/pc#patch-58625
