### ISSUE TITLE
JJonak Zen-Makji Skin

### ISSUE THREAD

**Issue by slowthgt** [Js41637/Overwatch-Item-Tracker#310]
This is another edge case, but since we added the all stars skins, we should add this one too?

**Comment by slowthgt** [comment]
Oh, also the portrait and spray for the ffa dead match season 2. I might just go to datatool, get it and make a pull.

**Comment by Js41637** [comment]
Ye dunnno what to do with this skin

**Comment by Js41637** [comment]
Ye dunnno what to do with this skin

**Comment by xathon** [comment]
I think it should be included with the skins, since the Lúcio OWL emote is too. Same for the new Winston skin.

**Comment by hectorevil** [comment]
JJonak Zen-Makji Skin,  Flying Ace Winston Skin, DoomFist Thunder Skin

**Comment by DracoClaw** [comment]
Will these skins be added? I know you have some issue with the team skins, especially now that some have changed. But whats the issue with adding these skins and emote?

**Comment by Js41637** [comment]
added
