### ISSUE TITLE
Add Sigma

### ISSUE THREAD

**Issue by Harmon758** [Js41637/Overwatch-Item-Tracker#319]
Patch 1.39.1.0
https://playoverwatch.com/en-us/news/patch-notes/pc#patch-60993

Also player icons and sprays for Season 18.

**Comment by Js41637** [comment]
added. just missing emotes and intros

**Comment by Vorboid** [comment]
Should this be closed now?

**Comment by Harmon758** [comment]
Emotes and intros were added with #321
