### ISSUE TITLE
Sigma achievements description shows Baptiste achievements instead.

### ISSUE THREAD

**Issue by Zedriodor** [Js41637/Overwatch-Item-Tracker#320]
When mousing over the Sigma sprays, cute and pixel, the description shows Baptiste's achivements are instead of Sigmas. 
![image](https://user-images.githubusercontent.com/1644433/63097467-da0f5580-bfb3-11e9-8fba-6fa57ecda47e.png)
![image](https://user-images.githubusercontent.com/1644433/63097484-e4315400-bfb3-11e9-98d3-82eecfa5e85a.png)

**Comment by Js41637** [comment]
Has been fixed.
