### ISSUE TITLE
Add 2019 Halloween events

### ISSUE THREAD

**Issue by xathon** [Js41637/Overwatch-Item-Tracker#323]
The Halloween event includes some more skins and items

https://playoverwatch.com/en-us/events/halloween-terror

**Comment by Harmon758** [comment]
They've already been added:
https://js41637.github.io/Overwatch-Item-Tracker/#/events/HALLOWEEN
https://github.com/Js41637/Overwatch-Item-Tracker/commit/d67a86fe0ffadc60f1de8ed00c3aab1c178ee1ff

**Comment by xathon** [comment]
I'm sorry, it didn't refresh this on my PC for some reason.

**Comment by Harmon758** [comment]
Yeah, sometimes it gets cached and you have to do a hard refresh after an update.
