### ISSUE TITLE
Winter Wonderland Small incorrections

### ISSUE THREAD

**Issue by slowthgt** [Js41637/Overwatch-Item-Tracker#331]
- Doomfist' skin is missing the "group": "WINTER_WONDERLAND_2019", and so, it's marked as 1k credits.
- Week 1 and 2's Player Icon and Spray are absent from the event page.
- Week 3's Spray is absent from the event page.
Last 2 points seem to be missing on events.json and possibly missing the "group": "WINTER_WONDERLAND_2019" too.

**Comment by 00dwan** [comment]
Also there are 2 voice lines now for Baptiste called "Some Kind of Angel."  One is a new one for the winter event and one is an old standard one.  I think it's causing a bug because the winter wonderland page has the non event one, and if you go to the Baptiste page, none of his voicelines show up.

**Comment by Js41637** [comment]
Thanks, Fixed. All these special timed items really screw things up.
