### ISSUE TITLE
Archives 2020. Spray "Strike" is missing

### ISSUE THREAD

**Issue by mishamyte** [Js41637/Overwatch-Item-Tracker#341]
_The "Strike" spray was added as a part of "Archives 2020" event. It is the spray, available for all heroes._ 

It is missing in the current release of OIT.

![ScreenShot_20-03-15_14-39-52-000](https://user-images.githubusercontent.com/5649656/76701630-7d038b80-66cb-11ea-9326-79c2a9f0c83c.jpg)

**Comment by Js41637** [comment]
All general and all class unlocks are currently missing. They will be added soon.

**Comment by Js41637** [comment]
fixed
