### ISSUE TITLE
Icons are sorted Alphabetically

### ISSUE THREAD

**Issue by DracoClaw** [Js41637/Overwatch-Item-Tracker#350]
The Icons in All Heros are sorted alphanumerically and not in the order they appear in game.

**Comment by Js41637** [comment]
This is intentional. The way they're ordered in the game makes no sense. Why would I do it that way?

**Comment by DracoClaw** [comment]
While this is true and the order is pretty shit in game. It's very hard to keep track of icons when they are in a different order. I can't just go down the list and check things off. Maybe an option to sort it like in game would be helpful

**Comment by Js41637** [comment]
The order in the game literally has no logic to it, i couldn't reproduce it even if i wanted to, i have no idea how it's sorted.

**Comment by DracoClaw** [comment]
Unless they are constantly changing, which I doubt they are, why not go through once and order it, and then be done.

**Comment by DracoClaw** [comment]
A new update has come out that properly sorts Player Icons. Can that order be applied in app?

**Comment by Js41637** [comment]
I'm not changing the order of the icons at this time.

**Comment by DracoClaw** [comment]
👌 Okay
