### ISSUE TITLE
Some event achievement skins incorrectly count towards max items when not selected

### ISSUE THREAD

**Issue by Trixter313** [Js41637/Overwatch-Item-Tracker#351]
Hello, I am having an issue where the game says I have 19/19 Junkrat skins but the tracker says 19/20. I believe it is due to the Inferno skin being counted towards the max items even when unselected, while the game does not.

**Comment by Trixter313** [comment]
Same goes for Mei's Zhongguo skin.

**Comment by Js41637** [comment]
This happens for all the limited time event skins/sprays/icons you get for playing games. Not sure when i'll be able to fix it.

**Comment by Trixter313** [comment]
Ok, I'll add any others I find for when you get around to it.

**Comment by Js41637** [comment]
should be fixed

**Comment by Trixter313** [comment]
Yep, all my numbers match up now! Thanks for the quick fix.
