### ISSUE TITLE
JSON Inconsistency 

### ISSUE THREAD

**Issue by DracoClaw** [Js41637/Overwatch-Item-Tracker#359]
The Backup Generator gives a different JSON than the one the tracker uses. The tracker starts with Ana, and the generator starts with Reaper. This makes it very difficult to compare and merge the two. If there was a system in place that event and exclusive items that arent supplied by the generator do not get overwritten this would not be an issue.

**Comment by Js41637** [comment]
I will look into this but this issue is kinda already tracked in #297 so i'll close this

**Comment by Js41637** [comment]
dub

**Comment by DracoClaw** [comment]
Awesome! Thank you <3
