### ISSUE TITLE
[Bug] Wrong count on Anniversary sprays

### ISSUE THREAD

**Issue by xathon** [Js41637/Overwatch-Item-Tracker#374]
![image](https://user-images.githubusercontent.com/36819668/120047592-3fabc500-c015-11eb-91d6-2f4a3ff9d031.png)

There are 52 sprays, but only a maximum of 49 is displayed.

Edit: the same goes for the Player Icons and skins. Maybe an issue with the 3 weekly challenges?

**Comment by Js41637** [comment]
should be fixed, its just a visual issue
