### ISSUE TITLE
Doomfist sprays

### ISSUE THREAD

**Issue by Omwtoomfg** [Js41637/Overwatch-Item-Tracker#375]
Hello.
I have issue with Doomfist sprays. It seems for me that way:
https://imgur.com/a/rYidrhZ
Also i didnt see new spray called "thumbs down" in anniversary event. It shows only the old version of the spray that belongs to the archives. I think the problem is that both sprays have the same name.
The backup contains only one mention of such a spray.
Unfortunately I can’t help with the code only to indicate the problem. Thank you for your work.

**Comment by Js41637** [comment]
thanks for spotting, indeed an issue caused by two items with the same name. it has been fixed.
