### ISSUE TITLE
Summer Games 2021

### ISSUE THREAD

**Issue by ozipone** [Js41637/Overwatch-Item-Tracker#378]
https://playoverwatch.com/en-us/events/summer-games/

**Comment by megascorcher** [comment]
There seems to be no progress on adding this year's Summer Games event items?

**Comment by PhilAnders** [comment]
Wasn't going to say anything since it takes time to upload all of the new stuff, but the event is all but over now. Will there be an update soon?

**Comment by palex00** [comment]
Back in the day this stuff was updated a mere day after the event began. And now.. is the tracker dead? Does anybody know any alsternatives?

**Comment by Egnosa** [comment]
If the developers dropped the project it would be nice to see an announcement at least.

**Comment by Js41637** [comment]
The data has been added.
