### ISSUE TITLE
Legendary skins in "by hero" have misplaced checkboxes

### ISSUE THREAD

**Issue by Kanegasi** [Js41637/Overwatch-Item-Tracker#38]
Here's D.Va for an example: http://i.imgur.com/JdsFVxo.png

All seven legendary skins do this. On Mei, there's also only one checkmark even though both skins are checked.

Chrome Version 55.0.2883.87 m (64-bit)

**Comment by Js41637** [comment]
Ah right, I forgot to fix this. Thanks.
