### ISSUE TITLE
Incorrect Competitive CTF Hero 2019 spray display (Missing Top 500 icon inside it)

### ISSUE THREAD

**Issue by FableBird** [Js41637/Overwatch-Item-Tracker#381]
I am aware that you do not try adding animated Competitive Hero sprays and I don't mind that. This is not the animated one, however did you know that the only difference between this spray and the Competitive CTF Competitor 2019 spray is that there's a Top 500 icon above it?

That Top 500 icon is not displayed in the Competitive CTF Hero 2019 spray and are exactly the same as the competitor one. Wonder if you can add that at least.

**Comment by Js41637** [comment]
fixed

**Comment by FableBird** [comment]
I still haven't seen the spray fixed yet. Does it take time to update?

**Comment by Js41637** [comment]
Yes. Images can be cached for several days.

**Comment by FableBird** [comment]
Okay thanks for letting me know
