### ISSUE TITLE
Echo's Golden Weapon display still missing

### ISSUE THREAD

**Issue by FableBird** [Js41637/Overwatch-Item-Tracker#383]
I usually wait for recently new seasonal event cosmetics to be displayed since I noticed some of them, especially emotes or highlight intros take some time to be recorded or captured.

However it's been over an year now since Echo was released and her golden weapon still hasn't been displayed. Is there some trouble you found digging through her models to find her golden arms?

**Comment by Js41637** [comment]
No its jsut hard to render them, i don't do it myself. I get a friend to do it and I just never asked them. I'll see if I can get a render made of her golden weapon thoughj, it's also her arm so it might be kind of hard...

**Comment by FableBird** [comment]
I understand. I was just curious why it hasn't been there, but take your time, especially if it could be difficult to render.

**Comment by Js41637** [comment]
dun, updated all the others as well
