### ISSUE TITLE
Mccree name change

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#391]
Mccree's name has changed to "Cassidy" and the hero's location has also been moved accordingly.

**Comment by FableBird** [comment]
> Yes all this data is automatically generated from the game, i don't need to manually change anything really. Names and descriptions will just update automatically. Items that have been renamed will cause issues though as item ids are generated based off their name so if the name changes then the id changes.
> 
> I don't think i'll be making any changes for now until the next event.

Are you going to make any changes now lately? It's been about 2 weeks since Winter Wonderland 2021 event started.

**Comment by FableBird** [comment]
Are you going to make any changes now lately? It's been about 2 weeks since Winter Wonderland 2021 event started.

**Comment by Js41637** [comment]
Updated

**Comment by FableBird** [comment]
Cassidy's "The Name's" and "Wanted" spray display still hasn't been updated yet. But I don't know whether or not the update of these are delayed or something.

**Comment by Js41637** [comment]
they have been updated

**Comment by FableBird** [comment]
The update might have been delayed then. I'll give you a thumbs up once I see the update.
