### ISSUE TITLE
Winter Wonderland 2021 Update

### ISSUE THREAD

**Issue by FableBird** [Js41637/Overwatch-Item-Tracker#393]
I know I posted this a bit early before the event starts. But it's very likely to come around 8 more hours.

**Comment by FableBird** [comment]
Besides all the new Winter stuff. I think all the new things besides that are just Season 32 sprays and icon as well as for Competitive No Limits 2021 and "Gladiators Unleashed" Spray

**Comment by korgen63** [comment]
No update since 2 weeks, I'm afraid this page is dead :(

**Comment by FableBird** [comment]
> No update since 2 weeks, I'm afraid this page is dead :(

I don’t claim that the page is dead yet unless it hasn’t been updated for years or something. Probably just really really delayed for now.

**Comment by Js41637** [comment]
updated
