### ISSUE TITLE
"Talon Spotted" spray price incorrect

### ISSUE THREAD

**Issue by FableBird** [Js41637/Overwatch-Item-Tracker#394]
Somehow it shows that this spray costs 25 credits while you actually cannot get this spray unless you have watched twitch streams for at least 4 hours when the New Blood challenge was going on.

**Comment by FableBird** [comment]
Are you fixing it? Seems like this issue is closed before that.

**Comment by Js41637** [comment]
It was fixed.

**Comment by FableBird** [comment]
Got the update. Thanks :)
