### ISSUE TITLE
Lunar New Year 2022 (Year of the Tiger) Update

### ISSUE THREAD

**Issue by AquaRyu** [Js41637/Overwatch-Item-Tracker#395]
Surprisingly there are only 2 new legendary lunar skins this year, Mercy and Tracer... Other than the 5th competitive icons and sprays for Capture the Flag, it shouldn't be too difficult to update overall.

**Comment by AquaRyu** [comment]
> Overwatch Item Tracker is dead :( :( :(

I think it really is dead if it hasn't updated for more than an year... sadly. But I'm just gonna keep waiting I guess. I just really hope Js41637 comes back soon.

**Comment by Js41637** [comment]
added
