### ISSUE TITLE
Reaper's Code of Violence Challenge Update

### ISSUE THREAD

**Issue by AquaRyu** [Js41637/Overwatch-Item-Tracker#396]
I hope you're not away for such a long time. But Reaper's Mini event has just been added today along with the Season 33 competitive sprays and icons. Hope you update the Lunar stuff as well asap.

**Comment by Narutoss15** [comment]
Hey admin, could you learn us, go to do updates and push it on github? We could help you with content if you don't have so much time for this project.

**Comment by Js41637** [comment]
added
