### ISSUE TITLE
Sombra Zhulong skin and Competitive 6v6 Elimination 2022

### ISSUE THREAD

**Issue by AquaRyu** [Js41637/Overwatch-Item-Tracker#397]
Just another legendary league skin for Sombra and another sprays and icon for Competitive. Both having one for competitor and another one for hero top 500...

**Comment by Narutoss15** [comment]
Hey @Js41637 , could you learn us, go to do updates and push it on github? We could help you with content if you don't have so much time for this project.

**Comment by Js41637** [comment]
added
