### ISSUE TITLE
Overwatch Anniversary Remix: Vol 3 Update and Medic Brigitte Skin

### ISSUE THREAD

**Issue by AquaRyu** [Js41637/Overwatch-Item-Tracker#408]
Just 6 recolored Legendary skin, Season 36 competitive sprays and icons. and a Medic Brig skin awarded to those subscribing Twitch streamers. And a Founder Player Icon, along with a Jester Sombra and General Doomfist skin that goes with the Founder's pack.

**Comment by Narutoss15** [comment]
Hey! You do update site before Overwatch 2?

**Comment by Js41637** [comment]
added
