### ISSUE TITLE
Zenyatta's Every Rooster Crows voiceline missing

### ISSUE THREAD

**Issue by Sasha2k1** [Js41637/Overwatch-Item-Tracker#43]

**Comment by Sasha2k1** [comment]
After thorough examination I assume that the checkmark is obscured by the player icon field
![screenshot_17](https://cloud.githubusercontent.com/assets/25538767/22610468/99b4640e-ea76-11e6-9dbe-b2446b25d5ae.png)

**Comment by Js41637** [comment]
This seems to be an issue with Firefox, honestly I've never even tested the website in Firefox and I'm surprised there hasn't been more issues. I'll look into it.

**Comment by Js41637** [comment]
I think I fixed this issue, is it fixed for you?
