### ISSUE TITLE
Copy/edit of save date doesn't work in firefox

### ISSUE THREAD

**Issue by dargaCode** [Js41637/Overwatch-Item-Tracker#54]
As far as I can tell there's no way to back up the data in Firefox. 

I tried right clicking to copy and paste, selecting all, ctrl C. 

Love this project and I use it all the time!

**Comment by Js41637** [comment]
Oh great another annoying Firefox issue, as you probably noticed I've never actually tested the site on Firefox and i'm surprised there hasn't been more issues. I'll fix it.

**Comment by Js41637** [comment]
Fixed it for me, let me know if there's still a problemo.

**Comment by dargaCode** [comment]
Yeah I know that feel for sure. 

Fixed now, thanks!
