### ISSUE TITLE
Add an achievement sub-header

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#56]
Would be easier to spot the items that are unlocked from an achievement.

There is no need to change the layout, just add a sub-header under the item's name with the word "Achievement" (or something similar):
```
<Item name>
<Achievement sub-header>
```

This will be similar to all other items that use this layout:
```
<Character name>
<Item name>
```

Edit: 
Looking at the Winter Wonderland, the sprays for each character are shown together, while the achievement spray is shown alone. This means that there is space for an extra box.

An additional optional feature could be to add the achievement itself right next to the spray.

**Comment by Js41637** [comment]
I could possibly add an `[Achievement]` tag next to those items, have to see how much room I have though, it will work well on the optional theme but I have limited space on the standard theme.

**Comment by Gonzom** [comment]
Didn't notice they were showing different data, thought it was only the holiday theme that changed. But yeah, I was using the Holiday Theme.

**Comment by Js41637** [comment]
They all use the same data it's just displayed differently along with some CSS tricks, but they both use the same HTML and data.
