### ISSUE TITLE
Bug: Standard Theme is showing a price for the Summer Games Legendary skins

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#58]
The Standard Theme is showing a price for the Summer Games Legendary Skins, but if I'm not mistaken (and the fact that there is no total price counter for this event) you couldn't buy them, only get them from crates.

**Comment by Js41637** [comment]
Indeed, was an oversight when I made the Legendary/Image Preview HTML global across all events.
