### ISSUE TITLE
Halloween event name incorrect

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#59]
I just noticed that for the Winter Wonderland event, you used the the full event name instead of Christmas, but for Halloween Terror you just used Halloween.

**Comment by Js41637** [comment]
So I was about to come in here and say I am aware of da slight problemo with the name and that I would change it if I could as changing the name means I need to update the data and it would be too much effort

Of course it wasn't until I realized that my pure genius has already solved this problem.

tl;dr Thanks for bringing this too my attention, I have renamed it in my testing versions and whenever it gets finished it will be pushed to live.
