### ISSUE TITLE
Add Overwatch Uprising event items

### ISSUE THREAD

**Issue by cinnamennen** [Js41637/Overwatch-Item-Tracker#60]
pretty much what the title says

**Comment by Js41637** [comment]
![image](https://cloud.githubusercontent.com/assets/6258213/24928030/4d609da4-1f44-11e7-8d47-d80fbbd7ca0d.png)

**Comment by drallieiv** [comment]
+1

**Comment by Apache1224** [comment]
How's this coming along? I haven't opened any boxes yet but I have a lot waiting until this is done.

**Comment by Js41637** [comment]
Well technically it's done, it's just some small things I would like to do and test the migration. It should be live in an hour or so.

**Comment by TSFaranae** [comment]
Keep up the good work! :)
