### ISSUE TITLE
Mine didn't migrate properly

### ISSUE THREAD

**Issue by atomicproton** [Js41637/Overwatch-Item-Tracker#63]
Console data:
`Starting Migrations
app.js:171 Running Migrations
app.js:180 Running Fix Ornament Sprays migration
app.js:180 Running Fix voice, poses and skins mappings migration
app.js:180 Running Convert Halloween and SummerGames to new Data migration
app.js:180 Running Fix Bokimario migration
app.js:180 Running Rename events to their proper IDs migration
app.js:180 Running Update event item IDs and rename new Rooster IDs migration
app.js:180 Running Move all event data to hero data migration
app.js:150 Uncaught TypeError: Cannot set property 'Track & Field' of undefined
    at Object.run (https://js41637.github.io/Overwatch-Item-Tracker/js/app.js:150:41)
    at https://js41637.github.io/Overwatch-Item-Tracker/js/app.js:181:9
    at Array.forEach (native)
    at https://js41637.github.io/Overwatch-Item-Tracker/js/app.js:178:14
    at Object.invoke (https://js41637.github.io/Overwatch-Item-Tracker/js/vendor/angular.min.js:43:171)
    at https://js41637.github.io/Overwatch-Item-Tracker/js/vendor/angular.min.js:45:80
    at q (https://js41637.github.io/Overwatch-Item-Tracker/js/vendor/angular.min.js:7:351)
    at db (https://js41637.github.io/Overwatch-Item-Tracker/js/vendor/angular.min.js:45:59)
    at c (https://js41637.github.io/Overwatch-Item-Tracker/js/vendor/angular.min.js:21:19)
    at Mc (https://js41637.github.io/Overwatch-Item-Tracker/js/vendor/angular.min.js:21:332)
services.js:30 Init StorageService
services.js:85 Fetching Data
services.js:49 Initializing`

And this was my actual data:
'{"SUMMER_GAMES_2016":{"skinsLegendary":{"Track & Field":true,"Champion":true},"skinsEpic":{"Nihon Genji":true,"American Mccree":true},"emotes":{"Boxing Bastion":true},"intros":{"Shotput Junkrat":true},"sprays":{},"voicelines":{},"poses":{},"icons":{}},"HALLOWEEN_2016":{"skinsLegendary":{"Witch Mercy":true,"Monster Roadhog":true,"Pumpkin Reaper":true},"skinsEpic":{"Ghoul Ana":true},"emotes":{},"intros":{},"sprays":{},"voicelines":{},"poses":{},"icons":{}},"WINTER_WONDERLAND_2016":{"skinsLegendary":{"torbjorn-santaclad":true,"winston-yeti":true,"zenyatta-nutcracker":false,"mei-meirry":false,"tracer-jingle":true},"skinsEpic":{"mccree-scrooge":true,"reaper-shiver":true,"pharah-frostbite":true,"lucio-andes":true},"emotes":{"zarya-mystery-gift":false,"mei-snowman":true},"intros":{"symmetra-snowflakes":true,"widowmaker-under-the-mistletoe":true},"sprays":{"bastion-ornament":true,"snowmei":true,"snowreaper":true,"reinhardt-ornament":true,"lucio-ornament":false,"lucio-hockey":false,"widowmaker-ornament":true,"sombra-ornament":true,"hanzo-ornament":true,"mei-ornament":true,"dva-cookie":false,"dva-ornament":true,"ana-warm":true,"winter-wonderland":true,"mercy-snow-angel":true,"mercy-ornament":true,"tracer-snowboarding":true,"tracer-ornament":true,"widowmaker-skiing":true,"zenyatta-snowball-fight":true},"voicelines":{"ana-im-watching-out-for-you":false,"dva-aw-you-shouldnt-have":true,"soldier-76-stay-frosty":true,"tracer-its-in-the-bag":true,"genji-merry-christmas":true,"mercy-your-guardian-angel":true,"widowmaker-exquisite":true},"poses":{"mercy-mistletoe":true,"reinhardt-toast":true,"soldier-76-toast":true,"torbjorn-toast":true,"ana-toast":true,"pharah-toast":true,"dva-festive":true},"icons":{"tracer-jingle":true,"pachireindeer":true,"present":true,"winter-wonderland":true,"bubbly":true,"gingerbread":true,"zenyatta-nutcracker":true}},"YEAR_OF_THE_ROOSTER_2017":{"skinsEpic":{"tracer-rose":true,"ana-tal":true,"bastion-rooster":true,"junkrat-firework":true,"mercy-golden":true},"sprays":{"mercy-parasol":true,"bastion-bastyum":true,"tracer-dragon-dance":true,"auspicious-lion":true,"awakened-lion":true,"year-of-the-rooster":true,"widowmaker-dragon-dance":true,"torbjorn-dragon-dance":true,"mercy-dragon-dance":true,"tracer-fan-dance":true,"widowmaker-hairpin":true,"roadhog-steamed-buns":true,"roadhog-dragon-dance":true,"red-envelope":true,"lucky-pouch":true,"dragons-head":true,"dva-seesaw":true,"dva-dragon-dance":true,"hanzo-dragon-dance":false,"hanzo-blue-dragon":true,"junkrat-im-flying":true,"mccree-call-it":true},"icons":{"fuchimari":true,"fortune":true,"year-of-the-rooster":true,"dva-hanbok":true,"lunamari":true,"seollal":false,"zenyatta-sanzang":true,"have-fish":true},"emotes":{"dva-bow":true,"junkrat-dud":true,"mei-so-excited":true},"poses":{"ana-folded-hands":true,"roadhog-whats-mine-is-mine":true,"dva-lucky-pouch":true},"skinsLegendary":{"dva-palanquin":true,"mei-luna":true,"reinhardt-wujing":false},"voicelines":{"zarya-get-pumped":true,"mercy-a-most-impressive-display":true,"tracer-ready-for-some-fireworks":true,"widowmaker-you-have-my-attention":true,"dva-the-best-things-in-life":true},"intros":{"mercy-fortune":true,"tracer-lion-dance":true}}}'

Also, migration was set to [0,1,2,3,4]

**Comment by Js41637** [comment]
These SummerGames and Halloween data is really screwing me over. I'll have a look at why they're not getting converted properly.

**Comment by Js41637** [comment]
Ok I think I got it, seeing as the error probably stopped any data changing, (if it did just copy your backup data into the `data` key) and delete the migrations key. Reload the site and it should migrate properly now.

**Comment by atomicproton** [comment]
Ok, it worked now.
