### ISSUE TITLE
Change hero item categories to match in-game order

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#64]
Issue: Currently, when viewing a Hero, the item category order will be:
Skins -> Emotes -> Intros -> Icons -> Sprays ->Voicelines ->Poses.
This is counter to what a user is expecting when filling out the data, as in-game the categories are:
Skins-> Emotes -> Victory Poses -> Sprays -> Highlight Intros -> Weapons

Current: Skins -> Emotes -> Intros -> Icons -> Sprays -> Voicelines -> Poses
Expected: Skins -> Emotes -> Victory Poses -> Sprays -> Highlight Intros -> Weapons -> Icons

Side note: Very great additions. Thanks!

**Comment by Js41637** [comment]
I agree it would be nice to have them in order however this does not work well. The layout is automatically 'positioned' (still in order) to try and fit evenly across all the categories, with the proper layout you end up getting something like this;
![image](https://cloud.githubusercontent.com/assets/6258213/24988377/ea240360-2048-11e7-923c-39ecb51e1f08.png)
which looks pretty crap.
