### ISSUE TITLE
Add Weapons category

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#65]
Since you've added every item in the game, but the weapons, it would be great if you could add them.
This can be done in several ways:

Option 1: Very basic, just add one version of the gun.
Option 2: If a skin has a variation of the weapon then add all variations. Example is Reinhardt with an axe.
Option 3: Add each skin's Golden weapon.

But at the very least add the option to check off and view the weapon.

**Comment by Js41637** [comment]
I was gonna add the weapon category but the only point in adding it would be for the Golden weapon, i think think it's gonna look stupid having a weapons section with 1 item and I think the minority of people would even have golden weapons. I'll think about it.

**Comment by particlePaul** [comment]
I recently manually copied my inventory data from the Hero Gallery to Overwatch Item Tracker. After completing each character, I'd compare the counts (e.g. `52/77`) as a check that I'd copied correctly, but I had to account for (1) the Hero Gallery not including icons and (2) Overwatch Item Tracker not including gold weapons.

It's not a big deal, but it would be nice to have that bit of collection data here.

**Comment by Js41637** [comment]
Well Gold Weapons aren't the issue here as it's only 1 (and most people don't even have golden weapons so the selected count would still be the same). I am working on a new version though which refactors how the cost and totals are calculated with the option to not include Icons in the totals and add item counts to the Home page as well as other data, i'm not sure when it will be ready though.

**Comment by Js41637** [comment]
As of the new version of the site there is an option in the settings page to not include items in the total, this will make the item counts on the home match the counts in Overwatch - 1.

There is however some exceptions, Overwatch does not count certain (all?) Blizzard promotional skins towards the total if you do not own it. For example I do not own the Blizzcon 2016 skin for Bastion however it says he has a total of 15 skins which is incorrect, it is not counting the Blizzcon skin towards the total.

**Comment by ziozxzioz** [comment]
I am really for this "adding weapons" feature, it's currently the only thing that bugs me about the project. I'd love it if you'd reconsider adding that weapons category!

**Comment by Js41637** [comment]
This has been added
