### ISSUE TITLE
Make it so that the icons and sprays overall synchronize with the character tabs

### ISSUE THREAD

**Issue by Apache1224** [Js41637/Overwatch-Item-Tracker#66]
.

**Comment by Js41637** [comment]
I don't quite understand.

**Comment by Apache1224** [comment]
You have to select all the the icons, and then go to the characters and select them again. It doesn't carry over

**Comment by Js41637** [comment]
Not sure if this was a massive oversight on my part, i'm so sure that it use to stay in sync but now I don't even know. It should be fixed now.
