### ISSUE TITLE
Peachimari Missing from Player Icons

### ISSUE THREAD

**Issue by Xrislord** [Js41637/Overwatch-Item-Tracker#73]
It's the only one I noticed that was missing :)

**Comment by Js41637** [comment]
Never heard of Peachimari

**Comment by Gonzom** [comment]
You have it under Lunarmari, but in-game its listed as Peachimari.

**Comment by riverhippo** [comment]
I think its a change the game made.  Because I remember getting Lunamari, but they changed the named apparently.

**Comment by KurtzPT** [comment]
I was about to write this, player icon Lunamari is actually called peachimari.

**Comment by Js41637** [comment]
Oh well, they didn't tell anyone they changed the name, they named Mercys Golden skin and Roadhogs Piggy (Pigsy) icon, they didn't mention the icon as well.

I'll try to fix this but it's a tad problematic as the item id can't change without a migration and i'm not gonna migrate for one item.
