### ISSUE TITLE
Missing "type" for general icons

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#74]
The Season 1-4 Hero, Competitor and Top 500 icons should have the achievement icon (or a new one if you find this misleading) as they are available only to those players who played comp during the season.

The Oni icon should have the Blizzard icon as it came from the same event as the skin.

**Comment by Js41637** [comment]
Fixed

**Comment by Gonzom** [comment]
You missed Top 500.

**Comment by Js41637** [comment]
DAMMIT

**Comment by Js41637** [comment]
gottem
