### ISSUE TITLE
Tracer - Missing icon

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#75]
The new Cadet icon is missing from Tracer's page.

**Comment by Js41637** [comment]
All new event icons are missing from hero pages as that data hasn't been added yet. All of this data has been semi-manually added for this event where as everything else is automagically generated. I might be able to fix this now or will have to wait until I can get it automatically generating

**Comment by Gonzom** [comment]
Ok, I won't add issues for new icons missing from heroes. Again, great job!

**Comment by Js41637** [comment]
Fixed
