### ISSUE TITLE
Mercy - Missing icons

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#78]
The Witch's Hat and Bewitching icons seem be related to Mercy (The Witch). The Hat can be seen on The Witch icon. Its similar to how the Hairpin icon was associated with Mei.

**Comment by Js41637** [comment]
While they may seem similar, the base data for all hero items are extracted from the game and is what you see in game when you unboxed these icons during the event, The Witch would say (Mercy) while the others were All or something so this is working as expected.

**Comment by Gonzom** [comment]
Never noticed that the icons have an in-game "class" that shows when you get it from the box, like other items do.

This would still be a great addition if it isn't that much work, as it will help players that are seeking items for a specific hero, to find them.
