### ISSUE TITLE
Add a few new fields to the All Classes filter

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#80]
In the All Classes page, it would be great if you could add some new fields to use with the filter.
These categories all have a unique theme which would make searching for these items much more easier.

Pachimari
Warcraft
Starcraft
Diablo
(Heartstone & Heroes of the Storm, even though they both have 1 each)

**Comment by Js41637** [comment]
Is this enough filters for you 
![image](https://cloud.githubusercontent.com/assets/6258213/24994889/1b84226a-2070-11e7-8e93-5ce88bfe0093.png)

**Comment by Gonzom** [comment]
Yeah its great! :)
