### ISSUE TITLE
Filter is missing the option to filter with "Blizzard"

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#82]
The filter is missing the option to filter with "Blizzard" unlockables.

**Comment by Js41637** [comment]
I can kinda see why you might want this but, I think for the hero views it's mostly useless only only a few heroes have Blizzard icons and they show up under the achievement filter anyway though I think it might be useful for the allclass...

**Comment by Gonzom** [comment]
Yeah, I was looking at the All Class for this, as I wanted to see the ones I can't get and had more Achievement stuff there than the ones I was actually looking for.
