### ISSUE TITLE
Uprising: event cost displaying incorrect value

### ISSUE THREAD

**Issue by AkimboJimbo229** [Js41637/Overwatch-Item-Tracker#83]
Chrome 57.0.2987.133, Win7 Pro

Event cost is showing as 33,225, not 36,825 credits. Looks like checking off Emotes and Victory Poses doesn't update the counter.

Initial screen: https://gyazo.com/a71f8a4e10f3e8d46c71c4a9a87b3839

Checked all poses/emotes: https://gyazo.com/e0c86d3ffbcb4a4316df8227e0035c43

Demonstrating that the counter does adjust for other items (checked Genji and Bastion skins): https://gyazo.com/da4b91ece74dce48048f1edfa1413b9c

**Comment by Js41637** [comment]
Ah yes, this was a stupid error by me, should be fixed.

**Comment by ehmuh** [comment]
Victory Poses counter is not fixed for me.

**Comment by Js41637** [comment]
Make sure you clear your cache (not cookies or site data), CTRL-F5 should work, it's working for me on the live site.

**Comment by AkimboJimbo229** [comment]
Looks good for me. Thanks! @Js41637
