### ISSUE TITLE
The "Season Hero" sprays are missing

### ISSUE THREAD

**Issue by Irv1n3** [Js41637/Overwatch-Item-Tracker#86]
The 4 sprays for "Season Competitor" are here but not the "Hero" counterpart.

No problem on the Icons side, the 8 icons are here.

**Comment by Js41637** [comment]
Do you mean the top 500 sprays? I can't extract the top 500 sprays as I don't think they are actual images, they are animated manually in-game to my knowledge though I could be wrong. The files i extract from the game call them Season X Competitor (which is the hero spray as you said). This data is automatically made, I dunno if I will be able to fix it.

**Comment by Js41637** [comment]
I added the season hero sprays however I don't have animated versions and truthfully adding gifs would cause problems. I wish I could though. Maybe if I could extract them from the game I would consider it.

**Comment by Gonzom** [comment]
@Js41637 Did you find out if you could extract the animated sprays?

**Comment by JarrodS846** [comment]
Unfortunately they cannot, there is no 'animated' images in the game at all, it's all rendered by the game so the animated sprays are split up into individual parts and spliced together and animated. So basically no chance of getting them.

**Comment by Js41637** [comment]
Unfortunately they cannot, there is no 'animated' images in the game at all, it's all rendered by the game so the animated sprays are split up into individual parts and spliced together and animated. So basically no chance of getting them.
