### ISSUE TITLE
Hero and Skin description

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#87]
Blizzard added new descriptions to all heroes and also to some of the skins. If its possible to add the Hero description to the top area and the skin description (for those that have it) to show when hovering over the skin, that would be very nice.

**Comment by Js41637** [comment]
Well uh, maybe if someone got me a a list as I really don't wanna preview every skin and write down the description.

**Comment by Gonzom** [comment]
Ana
General:
Former second in command of Overwatch, Ana Amari uses her skill and expertise to defend her home and the people she cares for.

Merciful:
Ana's biotic rifle uses a modified version of Mercy's healing technology, though the weapon was created against the doctor's wishes.

Shrike:
Recently, Ana has operated under the alias of "Shrike" and is wanted for espionage, assault, and theft in Egypt.

Captain Amari:
Captain Ana Amari was Strike Commander Morrison's second in command of Overwatch.

Horus:
Ana's call sign was "Horus" when she served in the Egyptian military during the Omnic Crisis.

**Comment by Gonzom** [comment]
Bastion
General: Once a frontline combatant in the Omnic Crisis, this curious Bastion unit now explores the world, fascinated by nature but wary of a fearful humanity.

Omnic Crisis:
During the Omnic Crisis, Bastion units fought against humans in battles around the world.

Null Sector:
Bastion unites were reengineered and upgraded by Null Sector and deployed during the King's Row uprising.

Overgrown:
Damaged in one of the battles of the Omnic Crisis, this lone Bastion unit was reactivated in the Black Forest near Eichenwalde years later.

**Comment by Js41637** [comment]
So as of commit bcb941153b214f0b648875bfc15d9dcda0f191cc skin descriptions are part of item data however I'm still not sure how to go about adding them to the site.

**Comment by Gonzom** [comment]
Really liked how to handled the skin descriptions. Good job.
For the Hero ones, you can add it to the right of the hero name at the top of the page (/under if using DirtDiglett's theme)

**Comment by Js41637** [comment]
I don't have hero descriptions, I'll see if it's possible for me to get these like I have gotten the others.

**Comment by Js41637** [comment]
So i've added hero descriptions to the data now as well and will look into placing it somewhere eventually.
