### ISSUE TITLE
Missing items from new filters

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#90]
Diablo
Icons: Lord of Terror, Lord of Candy
Sprays: Pinata

Warcraft
Icons: Varian
Sparys: Goldshire Pictures, You Are Not Prepared!
(On the fence about the Rikimaru icon and spray as its obvious its a reference to World of Warcraft and the Murloc race) 

Starcraft
Icons: 16 Bit Hero, Hierarch
Sprays: GL HF

(On the fence about the Siege Mode icon and spray as its obvious its a reference to Starcraft and the Marine unit)

**Comment by Js41637** [comment]
I dunno, some of these seem like a stretch to connect them, I just copied what they have listed on the wikis, gamepedia wiki is missing a lot of sprays but wikia one has the same Blizzard Themed icons. http://overwatch.wikia.com/wiki/Player_Icons http://overwatch.gamepedia.com/Player_Icons#General

**Comment by Js41637** [comment]
Sprays like 16 Bit Hero and Siege mode are references to the arcade area in Hamamura i believe, like the wikia lists then as map related icons.

**Comment by Gonzom** [comment]
I agree that the Siege Mode is a reference to the arcade, but that arcade was added as a direct reference to the actual game. Having said that, I did say I was on the fence about that one and the Rikimaru one.

Regarding the 16 Bit Hero one, that's Jim Raynor (even if it has an in-game reference).

**Comment by Js41637** [comment]
Ok I added most of them, thanks.
