### ISSUE TITLE
"You are not prepared" icon and spray do not change the stat numbers when selecting them

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#96]
In the All Classes, the "You are not prepared" icon and spray do not change the stat numbers when selecting them.

As a side note, there are a total of 261 icons and 94 sprays listed, but the total icon stat shows 258 and total spray stat shows 91, so 2 more icons and sprays might have the same issue.

**Comment by Js41637** [comment]
You are not prepared is a default icon, you're not meant to be able to select them, default icons are not included in the total.

**Comment by Js41637** [comment]
They should display like this?
![image](https://cloud.githubusercontent.com/assets/6258213/25029462/e37f7ac2-2100-11e7-853a-2286bbb28fb4.png)

**Comment by Gonzom** [comment]
I've further tested this. In list view you cannot unselect it, but in grid view you can.

Also, any specific reason why its not included in the total? In-game does not have any total showing for the icons, and the general sprays don't have their own category anyways, so its not likely to cause a conflict with the in-game total, but it does cause confusing here (as an example, use only the wow filter and see 0/0 sprays).

**Comment by Js41637** [comment]
Because the same code that handles all class handles heroes and hero default skins aren't included in totals.

**Comment by Js41637** [comment]
I will make them so they always show and hide the 0/0 if there is no items.

**Comment by Js41637** [comment]
I would add a check but I really don't want to add additional logic to the cost and total calculator as it's already quite a heavy function, it already lags on Firefox. Also I would like to keep it consistent as heroes don't count default items. The new fix I did should solve the issue though.  

So they will always be shown as selected now and will say `Item Name (Default)` in the tooltip.
