### ISSUE TITLE
Missing Voice Lines

### ISSUE THREAD

**Issue by InventivetalentDev** [Js41637/Overwatch-Item-Tracker#99]
Hey!

I've noticed that a few Voice Lines are missing while going through all the heroes in game. 
Some of the ones missing on the item tracker are:

- **Ana** Justice Delivered
- **D.Va** Love, D.Va
- **Junkrat** TIck-Tock-Tick-Tock
- **Lúcio** To the rhythm 
- **McCree** Watch and learn
... (probably some more, didn't check yet)
- **Soldier: 76** I've still got it
- **Törbjörn** Hard work pays off
- **Tracer** You got it
- **Zarya** Strong as the mountain
- **Zenyatta** We are in harmony

**Comment by Js41637** [comment]
These are default voicelines? They're at the top? 
![image](https://cloud.githubusercontent.com/assets/6258213/25203536/ed393a08-259c-11e7-8957-c5ef3089855e.png)

**Comment by InventivetalentDev** [comment]
Oh... lol! Sorry. 

Although it is slightly confusing to have the default one at the very top, instead of sorted alphabetically like in game. It works fine for the default _Heroic_ Emotes/Highlight Intros/Victory Poses, but it might be nice to also have the Voice Lines sorted like in game. :)

**Comment by Js41637** [comment]
I have it this way to keep it consistent, everything else has the default one at the top, just seems logical seeing as they are all displayed together that they follow the same layout.
